$(document).ready(function(){
		// code to add a sign to the vocabulary
		// {"signName":"", "cuneiform":"", "cuneiform1":"", "cuneiform2":"", "cuneiform3":"", "cuneiform4":"", "cuneiform5":"", "cuneiform6":"", "cuneiform7":"", "val":"\uD808\uDC2D"},
		// the list of cuneiform signs can be found here http://en.wikipedia.org/wiki/List_of_cuneiform_signs
		
    var vocabulary = [
	    {"signName":"AS", "cuneiform":"ASH", "cuneiform1":"asz", "cuneiform2":"as", "cuneiform3":"ash", "cuneiform4":"dil", "cuneiform5":"dili", "cuneiform6":"rum", "val":"\uD808\uDC38"},
		{"signName":"AS-AS", "cuneiform":"asz-asz", "cuneiform1":"min5", "val":"\uD809\uDC00"},
		{"signName":"HAL", "cuneiform":"HAL", "cuneiform1":"hal", "val":"\uD808\uDD2C"},
		{"signName":"AS-AS-AS", "cuneiform":"asz-asz-asz", "cuneiform1":"esz6", "val":"\uD809\uDC01"},
        {"signName":"BAL", "cuneiform":"bal", "val":"\uD808\uDC44"},
        {"signName":"GIR", "cuneiform":"GIR2", "cuneiform1":"gir","cuneiform2":"gir2", "cuneiform3":"giri2", "val":"\uD808\uDD08"},
		{"signName":"GIR-GUNU", "cuneiform":"GIR2-GUNU", "cuneiform1":"gir-gunu","cuneiform2":"gir2-gunu", "cuneiform3":"kiszi17", "cuneiform4":"tab2", "cuneiform5":"ul4", "val":"\uD808\uDD09"},
		{"signName":"BUR", "cuneiform":"BUR2", "cuneiform1":"bur","cuneiform2":"bur2", "val":"\uD808\uDC54"},
		{"signName":"TAR", "cuneiform":"tar", "cuneiform1":"hasz", "cuneiform2":"ku5", "cuneiform3":"kud", "cuneiform4":"kur5", "cuneiform5":"sila", "val":"\uD808\uDEFB"},
        {"signName":"AN", "cuneiform":"an", "cuneiform1":"DINGIR", "cuneiform2":"dingir", "cuneiform3":"am6", "cuneiform4":"il3", "val":"\uD808\uDC2D"},
		{"signName":"MUG", "cuneiform":"mug", "val":"\uD808\uDE2E"},
		{"signName":"MUG-GUNU", "cuneiform":"MUG-GUNU", "cuneiform1":"mug-gunu","cuneiform2":"zadim", "cuneiform3":"ZADIM", "val":"\uD808\uDE2F"},
		{"signName":"BA", "cuneiform":"ba", "cuneiform1":"be4", "val":"\uD808\uDC40"},
		{"signName":"ZU", "cuneiform":"zu", "cuneiform1":"su2", "val":"\uD808\uDF6A"},
		{"signName":"SU", "cuneiform":"su", "cuneiform1":"kusz", "cuneiform2":"sug6", "val":"\uD808\uDEE2"},
		{"signName":"SEN", "cuneiform":"sen", "cuneiform1":"szen", "cuneiform2":"SZEN", "cuneiform3":"SHEN", "cuneiform4":"shen", "cuneiform5":"dur10", "val":"\uD808\uDEBF"},
		{"signName":"ARAD", "cuneiform":"arad", "val":"\uD808\uDC34"},
		{"signName":"ARAD2", "cuneiform":"arad2", "cuneiform1":"ARAD2", "cuneiform2":"arad2", "val":"\uD808\uDC35"},
		{"signName":"ITI", "cuneiform":"iti", "cuneiform1":"itid", "val":"\ud808\udf17"},
		{"signName":"ITI2", "cuneiform":"iti2", "val":"\uD808\uDF1B"},
		{"signName":"SUBUR", "cuneiform":"SHUBUR", "cuneiform1":"subur", "cuneiform2":"shubur", "cuneiform3":"szubur", "cuneiform4":"SAH","cuneiform5":"szah", "val":"\uD808\uDEDA"},
		{"signName":"zu2", "cuneiform":"ka", "cuneiform1":"dug4", "cuneiform2":"duga4", "cuneiform3":"du11", "cuneiform4":"ga14", "cuneiform5":"giri17", "cuneiform6":"gu3", "cuneiform7":"inim", "val":"\uD808\uDD57"},
		{"signName":"KA-GIR2", "cuneiform":"ka-gir2", "cuneiform1":"ka-gir", "val":"\uD808\uDD68"},
		{"signName":"TU6", "cuneiform":"tu6", "cuneiform1":"KA-LI", "cuneiform2":"ka-li", "val":"\uD808\uDD72"},
		{"signName":"KA-TU", "cuneiform":"ka-tu", "val":""},
		{"signName":"KA-RU", "cuneiform":"ka-ru", "val":"\uD808\uDD7D"},
		{"signName":"KA-BAD", "cuneiform":"ka-bad", "cuneiform1":"US11", "cuneiform2":"us11", "cuneiform3":"ush11", "cuneiform4":"usz11", "val":"\uD808\uDD5C"},
		{"signName":"KA-BAR", "cuneiform":"ka-bar", "cuneiform1":"KA-MAS", "cuneiform2":"ka-mas", "cuneiform3":"ka-mash", "cuneiform4":"ka-masz", "val":"\uD808\uDD5E"},
		{"signname":"KA-NUN", "cuneiform":"ka-nun", "cuneiform1":"NUNDUM", "cuneiform2":"nundum", "val":"\uD808\uDD7B"},
		{"signName":"KA-SA", "cuneiform":"ka-sa", "cuneiform1":"SU6", "cuneiform2":"su6", "val":"\uD808\uDD7E"},
		{"signName":"PU", "cuneiform":"PU3", "cuneiform1":"pu3", "cuneiform2":"ka-kar", "cuneiform3":"ka-kar1", "val":"\ud808\udd64"},
		{"signName":"KA-NE", "cuneiform":"ka-ne", "val":"\ud808\udd7a"},
		{"signName":"KA-KIB", "cuneiform":"ka-kib", "val":"\ud808\udd6a"},
		{"signName":"KA-GAG", "cuneiform":"ka-gag", "val":"\uD808\uDD6F"},
		{"signName":"KA-US", "cuneiform":"ka-us", "cuneiform1":"ka-ush", "cuneiform2":"ka-usz", "val":"\uD808\uDD8B"},
		{"signName":"KA-PA", "cuneiform":"ka-pa", "val":""},
		{"signName":"KA-GIS", "cuneiform":"ka-gis", "cuneiform1":"ka-gish", "cuneiform2":"ka-gisz", "val":""},
		{"signName":"KA-SID", "cuneiform":"ka-sid", "cuneiform1":"ka-shid", "cuneiform2":"ka-szid", "val":"\uD808\uDD82"},
		{"signName":"KA-U", "cuneiform":"ka-u", "cuneiform1":"ka-u2", "val":"\uD808\uDD88"},
	{"signName":"KA-GA", "cuneiform":"ka-ga", "val":"\uD808\uDD62"},
	{"signName":"KA-SAR", "cuneiform":"ka-sar", "val":"\uD808\uDD7F"},
	{"signName":"KA-AS", "cuneiform":"ka-as", "cuneiform1":"ka-ash2", "cuneiform2":"ka-asz2", "val":"\uD808\uDD5B"},
	{"signName":"KA-DUB", "cuneiform":"ka-dub", "cuneiform1":"ka-dub2", "cuneiform2":"ka-balag", "cuneiform3":"KA-BALAG", "val":"\uD808\uDD5D"},
	{"signName":"KA-SA", "cuneiform":"ka-sa", "cuneiform1":"ka-sha", "cuneiform2":"ka-sza", "val":"\uD808\uDD80"},
	{"signName":"SUDU", "cuneiform":"shudu3", "cuneiform1":"szudu3", "cuneiform2":"ka-su", "cuneiform3":"ka-shu", "cuneiform4":"ka-szu", "val":"\uD808\uDD83"},
	{"signName":"KA-SE", "cuneiform":"ka-se", "cuneiform1":"ka-she", "cuneiform2":"ka-sze", "val":"\uD808\uDD81"},
	{"signName":"KA-UD", "cuneiform":"ka-ud", "val":"\uD808\uDD89"},
	{"signName":"KA-PI", "cuneiform":"ka-pi", "val":"\uD808\uDD7C"},
	{"signName":"KA-ERIM", "cuneiform":"ka-erim", "val":"\uD808\uDD60"},
	{"signName":"BUN", "cuneiform":"bun", "cuneiform1":"bun2", "cuneiform2":"KA-IM", "cuneiform3":"ka-im", "val":"\uD808\uDD6E"},
	{"signName":"KA-HAR", "cuneiform":"ka-har", "val":""},
	{"signName":"KA-U", "cuneiform":"ka-u", "val":"\uD808\uDD87"},
	{"signName":"KA-MI", "cuneiform":"ka-mi", "val":"\uD808\uDD78"},
	{"signName":"KA-ES", "cuneiform":"ka-esz", "val":""},
	{"signName":"KA-IGI", "cuneiform":"ka-igi", "val":"\uD808\uDD6D"},
	{"signName":"KA-KI", "cuneiform":"ka-ki", "val":"\uD808\uDD70"},
	{"signName":"EME", "cuneiform":"eme", "cuneiform1":"KA-ME", "cuneiform2":"ka-me", "val":"\uD808\uDD74"},
	{"signName":"KA-SE", "cuneiform":"ka-she3", "cuneiform":"ka-sze3", "val":"\uD808\uDD61"},
	{"signName":"KA-GUR7", "cuneiform":"ka-gur7", "val":"\uD808\uDD6C"},
	{"signName":"NAG", "cuneiform":"nag", "cuneiform1":"KA-A", "cuneiform2":"ka-a", "cuneiform3":"enmen2", "cuneiform4":"kab2", "cuneiform5":"na8", "val":"\uD808\uDD58"},
	{"signName":"GU7", "cuneiform":"gu7", "cuneiform1":"KA-NIG", "cuneiform2":"ka-nig", "cuneiform3":"ka-nig2", "val":"\uD808\uDD65"},
	{"signName":"KA-KADRA", "cuneiform":"ka-kadra", "val":"\uD808\uDD66"},
	{"signName":"KA-SIG", "cuneiform":"ka-sig","val":"\uD808\uDD84"},
	{"signName":"KA-GU", "cuneiform":"ka-gu", "val":"\uD808\uDD6B"},
	{"signName":"URU", "cuneiform":"IRI", "cuneiform1":"uru", "cuneiform2":"iri", "cuneiform3":"eri", "cuneiform4":"re2", "cuneiform5":"ri2", "cuneiform6":"u19", "val":"\uD808\uDF37"},
	{"signName":"URU-TU", "cuneiform":"uru-tu", "cuneiform1":"szeg5", "val":"\uD808\uDF4B"},
	{"signName":"UKKIN", "cuneiform":"ukkin", "cuneiform1":"uru-masz", "cuneiform2":"uru-bar", "val":"\uD808\uDF3A"},
	{"signName":"URU-KAR", "cuneiform":"uru-kar2", "val":"\uD808\uDF3E"},
	{"signName":"BANSUR", "cuneiform":"bansur", "cuneiform1":"banszur", "cuneiform2":"uru-urudu", "val":"\uD808\uDF4E"},
	{"signName":"SAKIR", "cuneiform":"szakir3", "cuneiform1":"URU-GA", "cuneiform2":"uru-ga", "val":"\uD808\uDF3C"},
	{"signName":"URU", "cuneiform":"uru2", "cuneiform1":"URU-UD", "cuneiform2":"uru-ud", "cuneiform3":"erim6", "val":"\uD808\uDF4D"},
	{"signName":"URU-UL", "cuneiform":"uru-ul", "val":"\uD808\uDF4C"},
	{"signName":"ASARI", "cuneiform":"asari", "cuneiform1":"URU-IGI", "cuneiform2":"uru-igi", "cuneiform3":"asal", "cuneiform4":"asar", "cuneiform5":"silig", "val":"\uD808\uDF42"},
	{"signName":"GISGAL", "cuneiform":"giszgal", "cuneiform1":"URU-MIN", "cuneiform2":"uru-min", "cuneiform3":"u18", "cuneiform4":"ulu3", "cuneiform5":"uru17", "val":"\uD808\uDF47"},
	{"signName":"URU-A", "cuneiform":"uru-a", "val":"\uD808\uDF38"},
	{"signName":"URU-HA", "cuneiform":"uru-ha", "val":"\uD808\uDF41"},
	{"signName":"ERIM", "cuneiform":"URU?NIG", "cuneiform1":"erim3", "cuneiform2":"uru-nig2", "val":"\uD808\uDF3F"},
	{"signName":"URU-GU", "cuneiform":"GUR5", "cuneiform1":"uru-gu", "cuneiform2":"gur5", "cuneiform3":"guru5", "cuneiform4":"gurusz3", "cuneiform5":"szakir", "val":"\uD808\uDF40"},
	{"signName":"LI", "cuneiform":"li", "val":"\uD808\uDDF7"},
	{"signName":"TU", "cuneiform":"tu", "cuneiform1":"du2", "cuneiform2":"tud", "cuneiform3":"tum12", "cuneiform4":"tur5", "val":"\uD808\uDF05"},
	{"signName":"KU4", "cuneiform":"ku4", "val":"\uD808\uDDAD"},
	{"signName":"GUR8", "cuneiform":"TE-GUNU", "cuneiform1":"gur8", "cuneiform2":"te-gunu", "cuneiform3":"uru5", "val":"\uD808\uDEFD"},
	{"signName":"LA", "cuneiform":"la", "cuneiform1":"szika", "val":"\uD808\uDDB7"},
	{"signName":"APIN", "cuneiform":"ENGAR", "cuneiform1":"apin", "cuneiform2":"engar", "val":"\uD808\uDC33"},
	{"signName":"MAH", "cuneiform":"mah", "val":"\uD808\uDE24"},
	{"signName":"PAB", "cuneiform":"PAP", "cuneiform1":"pab", "cuneiform2":"pap", "cuneiform3":"kur2", "cuneiform4":"pa4", "val":"\uD808\uDE7D"},
	{"signName":"GAM", "cuneiform":"GAM3", "cuneiform1":"gam3", "val":"\uD808\uDD9B"},
	{"signName":"MU", "cuneiform":"mu", "val":"\uD808\uDE2C"},
	{"signName":"SILA", "cuneiform":"qa", "cuneiform1":"sila3", "cuneiform2":"sal4", "val":"\uD808\uDEE1"},
	{"signName":"SESLAM", "cuneiform":"SZESZLAM", "cuneiform1":"szeszlam", "val":"\uD808\uDEC2"},
	{"signName":"GIL", "cuneiform":"gil", "cuneiform1":"gel", "cuneiform2":"gi16", "cuneiform3":"gib", "cuneiform4":"gilim", "val":"\uD808\uDD03"},
	{"signName":"KID", "cuneiform":"TAG4", "cuneiform1":"kid2", "cuneiform2":"tag4", "cuneiform3":"tak4", "cuneiform4":"taka4", "cuneiform5":"da13", "val":"\uD808\uDEFA"},
	{"signName":"KAD", "cuneiform":"kad2", "val":"\uD808\uDD90"},
	{"signName":"KAD", "cuneiform":"kad3", "val":"\uD808\uDD91"},
	{"signName":"NA", "cuneiform":"na", "val":"\uD808\uDE3E"},
	{"signName":"RU", "cuneiform":"ru", "cuneiform1":"ilar", "cuneiform2":"szub", "val":"\uD808\uDE92"},
	{"signName":"NU", "cuneiform":"nu", "cuneiform1":"sir5", "val":"\uD808\uDE61"},
	{"signName":"BAD", "cuneiform":"bad", "cuneiform1":"ba9", "cuneiform2":"be", "val":"\uD808\uDC41"},
	{"signName":"IDIM", "cuneiform":"idim", "val":"\uD808\uDD42"},
	{"signName":"TIL", "cuneiform":"til", "cuneiform1":"sumun", "cuneiform2":"szumun", "val":"\uD808\uDF00"},
	{"signName":"US", "cuneiform":"usz2", "cuneiform1":"ug7", "val":"\uD808\uDF57"},
	{"signName":"ESE", "cuneiform":"esze3", "val":"\uD809\uDC58"},
	{"signName":"SIR", "cuneiform":"szir", "cuneiform1":"asz7", "val":"\uD808\uDED3"},
	{"signName":"SIR-TENU", "cuneiform":"szir-tenu", "val":"\uD808\uDED4"},
	{"signName":"NUMUN", "cuneiform":"numun", "val":"\uD808\uDDB0"},
	{"signName":"NUMUN-GUNU", "cuneiform":"numun-gunu", "val":"\uD808\uDDB1"},
	{"signName":"TI", "cuneiform":"ti", "cuneiform1":"TI-TENU", "cuneiform2":"ti-tenu", "cuneiform3":"de9", "cuneiform4":"di3", "cuneiform5":"tig4", "cuneiform6":"til3", "val":"\uD808\uDEFE"},
	{"signName":"DIN", "cuneiform":"din", "cuneiform1":"kurun2", "cuneiform2":"tin", "val":"\uD808\uDC77"},
	{"signName":"MAS", "cuneiform":"masz", "cuneiform1":"mas", "cuneiform2":"mas", "cuneiform3":"sa9", "val":"\uD808\uDE26"},
	{"signName":"BAR", "cuneiform":"bar", "val":"\uD808\uDC47"},
	{"signName":"BAN", "cuneiform":"ban2", "val":"\uD809\uDC4F"},
	{"signName":"AG", "cuneiform":"ag", "cuneiform1":"ak", "val":"\uD808\uDC1D"},
	{"signName":"AG-SITA", "cuneiform":"ag-szita2", "val":"\uD808\uDC1F"},
	{"signName":"ME3", "cuneiform":"me3", "val":"\uD808\uDC1E"},
	{"signName":"MAS", "cuneiform":"masz2", "val":"\uD808\uDE27"},
	{"signName":"KUN", "cuneiform":"kun", "val":"\uD808\uDDB2"},
	{"signName":"HU", "cuneiform":"hu", "cuneiform1":"muszen", "cuneiform2":"pag", "cuneiform3":"u11", "val":"\uD808\uDD37"},
	{"signName":"NAM", "cuneiform":"nam", "val":"\uD808\uDE46"},
	{"signName":"IG", "cuneiform":"GAL", "cuneiform1":"ig", "cuneiform2":"gal2", "cuneiform3":"eg", "cuneiform4":"ek", "cuneiform5":"ik", "cuneiform6":"iq", "val":"\uD808\uDD45"},
	{"signName":"SZITA3", "cuneiform":"RAD", "cuneiform1":"szita3", "cuneiform2":"rad", "val":"\uD808\uDEE5"},
	{"signName":"ZI", "cuneiform":"zi", "cuneiform1":"se2", "cuneiform2":"si2", "cuneiform3":"ze", "cuneiform4":"zid", "cuneiform5":"zig3", "val":"\uD808\uDF63"},
	{"signName":"GI", "cuneiform":"gi", "cuneiform1":"ge", "cuneiform2":"gen6", "cuneiform3":"ke2", "cuneiform4":"ki2", "cuneiform5":"sig17", "val":"\uD808\uDD00"},
	{"signName":"GI-E", "cuneiform":"gi-e", "val":"\uD808\uDD01"},
	{"signName":"RI", "cuneiform":"ri", "cuneiform1":"dal", "cuneiform2":"de5", "cuneiform3":"re", "cuneiform4":"rig5", "val":"\uD808\uDE91"},
	{"signName":"NUN", "cuneiform":"nun", "cuneiform1":"eridug", "cuneiform2":"sil2", "cuneiform3":"zil", "val":"\uD808\uDE63"},
	{"signName":"NUN-TENU", "cuneiform":"nun-tenu", "val":"\uD808\uDE69"},
	{"signName":"NUN-NUN", "cuneiform":"LAGAR-LAGAR", "cuneiform1":"nun-nun", "cuneiform2":"lagar-lagar", "val":"\uD808\uDE6C"},
	{"signName":"TUR3-USZ", "cuneiform":"tur3-usz", "cuneiform1":"IMMAL", "cuneiform2":"immal", "val":"\uD808\uDE65"},
	{"signName":"TUR3-NIG2", "cuneiform":"tur3-nig2", "val":"\uD808\uDE64"},
	{"signName":"SILAM", "cuneiform":"szilam", "val":"\uD808\uDE66"},
	{"signName":"SILAM-SILAM", "cuneiform":"szilam-szilam", "val":"\uD808\uDE67"},
	{"signName":"KAB", "cuneiform":"kab", "val":"\uD808\uDC8F"},
	{"signName":"HUB2", "cuneiform":"hub2", "val":"\uD808\uDC38"},
	{"signName":"HUB", "cuneiform":"HUB-UD", "cuneiform1":"hub", "cuneiform2":"hub-ud", "val":"\uD808\uDC3D"},
	{"signName":"SUR", "cuneiform":"shur", "cuneiform1":"sur", "cuneiform2":"szur", "val":"\uD808\uDEE9"},
	{"signName":"MUS", "cuneiform":"MUSZ3-GUNU", "cuneiform1":"musz2", "cuneiform2":"musz3-gunu", "val":"\uD808\uDE3D"},
	{"signName":"MUSZ3", "cuneiform":"INANNA", "cuneiform1":"musz3", "cuneiform2":"inanna", "val":"\uD808\uDE39"},
	{"signName":"MUSZ3-A", "cuneiform":"musz3-a", "val":"\uD808\uDE3A"},
	{"signName":"SED", "cuneiform":"sed", "val":"\uD808\uDE3B"},
	{"signName":"GAD", "cuneiform":"gad", "cuneiform1":"gada", "val":"\uD808\uDCF0"},
	{"signName":"UMBIN", "cuneiform":"umbin", "val":"\uD808\uDF22"},
	{"signName":"SINIG", "cuneiform":"szinig", "val":"\uD808\uDED2"},
	{"signName":"KINDA", "cuneiform":"kinda", "val":"\uD808\uDCF1"},
	{"signName":"EN", "cuneiform":"en", "cuneiform1":"in4", "cuneiform2":"ru12", "cuneiform3":"uru16", "val":"\uD808\uDC97"},
	{"signName":"ENME", "cuneiform":"EN-ME", "cuneiform1":"enme", "cuneiform2":"en-me", "val":"\uD808\uDC9A"},
	{"signName":"EN-EN", "cuneiform":"en-en", "val":"\uD808\uDC9B"},
	{"signName":"4-EN", "cuneiform":"4-en", "val":"\uD808\uDC9D"},
	{"signName":"BURU14", "cuneiform":"buru14", "val":"\uD808\uDC98"},
	{"signName":"EN-KAR", "cuneiform":"GAN-TENU", "cuneiform1":"en-kar2", "cuneiform2":"gan2-tenu", "val":"\uD808\uDC99"},
	{"signName":"DAR3", "cuneiform":"dar3", "val":"\uD808\uDC70"},
	{"signName":"DIM", "cuneiform":"DIM", "val":"\uD808\uDC74"},
	{"signName":"DIM-SE", "cuneiform":"DIM-KUR", "cuneiform1":"dim-sze", "cuneiform2":"dim-kur", "val":"\uD808\uDC75"},
	{"signName":"BULUG", "cuneiform":"bulug", "val":"\uD808\uDC51"},
	{"signName":"MENBULUG", "cuneiform":"BULUG-BULUG", "cuneiform1":"menbulug2", "cuneiform2":"bulug-bulug", "val":"\uD808\uDC51"},
	{"signName":"LAL3", "cuneiform":"TA-HI", "cuneiform1":"lal3", "cuneiform2":"ta-hi", "cuneiform3":"alamusz", "val":"\uD808\uDEED"},
	{"signName":"KU7", "cuneiform":"ku7", "val":"\uD808\uDDAF"},
	{"signName":"SA", "cuneiform":"sa", "val":"\uD808\uDE93"},
	{"signName":"ASGAB", "cuneiform":"aszgab", "val":"\uD808\uDC3F"},
	{"signName":"GAN", "cuneiform":"gan2", "cuneiform1":"ga3", "cuneiform2":"gana2", "cuneiform3":"iku", "cuneiform4":"kan2", "val":"\uD808\uDCF7"},
	{"signName":"KAR", "cuneiform":"kar2", "cuneiform1":"gan2-tenu", "cuneiform2":"sze3-tenu", "cuneiform3":"guru6", "val":"\uD808\uDCF8"},
	{"signName":"GU", "cuneiform":"TIK", "cuneiform1":"gu2", "cuneiform2":"tik", "val":"\uD808\uDD18"},
	{"signName":"USAN", "cuneiform":"GU-NUN", "cuneiform1":"usan", "cuneiform2":"gu2-nun", "val":"\uD808\uDD1B"},
	{"signName":"DUR", "cuneiform":"GU-GAG", "cuneiform1":"dur", "cuneiform2":"gu2-gag", "val":"\uD808\uDD19"},
	{"signName":"GUR", "cuneiform":"gur", "val":"\uD808\uDD25"},
	{"signName":"SI", "cuneiform":"si", "cuneiform1":"sig9", "val":"\uD808\uDEDB"},
	{"signName":"SU4", "cuneiform":"SI-GUNU", "cuneiform1":"su4", "cuneiform2":"si-gunu", "cuneiform3":"sa11", "val":"\uD808\uDEDC"},
	{"signName":"DAR", "cuneiform":"GUN3", "cuneiform1":"dar", "cuneiform2":"gun3", "cuneiform3":"tar2", "val":"\uD808\uDC6F"},
	{"signName":"SAG", "cuneiform":"sag", "cuneiform1":"dul7", "cuneiform2":"sa12", "cuneiform3":"szak", "val":"\uD808\uDE95"},
	{"signName":"SAG-SAG", "cuneiform":"sag-sag", "val":"\uD808\uDEA7"},
	{"signName":"SAG-NUN", "cuneiform":"sag-nun", "val":"\uD808\uDE9E"},
	{"signName":"SAG-UM", "cuneiform":"sag-um", "val":"\uD808\uDEA4"},
	{"signName":"SAG-DU", "cuneiform":"sag-du", "val":"\uD808\uDE97"},
	{"signName":"SAG-GAG", "cuneiform":"sag-gag", "val":"\uD808\uDE9A"},
	{"signName":"SAG-US", "cuneiform":"sag-usz", "val":"\uD808\uDEA6"},
	{"signName":"DILIB3", "cuneiform":"SAG-SID", "cuneiform1":"dilib3", "cuneiform2":"sag-szid", "val":"\uD808\uDEA0"},
	{"signName":"SAG-U", "cuneiform":"sag-u2", "val":"\uD808\uDEA2"},
	{"signName":"SAG-UB", "cuneiform":"sag-ub", "val":"\uD808\uDEA3"},
	{"signName":"KAN3", "cuneiform":"SAG-MI", "cuneiform1":"kan3", "cuneiform2":"sag-mi", "val":"\uD808\uDE9D"},
	{"signName":"SAG-UR", "cuneiform":"sag-ur", "val":"\uD808\uDEA5"},
	{"signName":"SAG-A", "cuneiform":"sag-a", "val":"\uD808\uDE96"},
	{"signName":"SAG-HA", "cuneiform":"sag-ha", "val":"\uD808\uDE99"},
	{"signName":"SAG-MUNUS", "cuneiform":"sag-munus", "val":"\uD808\uDE9F"},
	{"signName":"SAG-LUM", "cuneiform":"sag-lum", "val":"\uD808\uDE9C"},
	{"signName":"MA", "cuneiform":"ma2", "val":"\uD808\uDE23"},
	{"signName":"UZ3", "cuneiform":"MA-KASKAL", "cuneiform1":"uz3", "cuneiform2":"ma2-kaskal", "cuneiform3":"ud5", "val":"\uD808\uDF5A"},
	{"signName":"UZ3-KASKAL", "cuneiform":"uz3-kaskal", "val":"\uD808\uDF5B"},
	{"signName":"SUR9", "cuneiform":"sur9", "val":"\uD808\uDEEA"},
	{"signName":"TAB", "cuneiform":"tab", "cuneiform1":"dab2", "cuneiform2":"tap", "val":"\uD808\uDEF0"},
	{"signName":"4-TAB", "cuneiform":"4-tab", "val":"\uD808\uDEF2"},
	{"signName":"ES21", "cuneiform":"TAB-AS", "cuneiform1":"esz21", "cuneiform2":"tab-asz", "val":"\uD809\uDC3B"},
	{"signName":"GESTIN", "cuneiform":"GIS-DIN", "cuneiform1":"gesztin", "cuneiform2":"gisz-din", "val":"\uD808\uDCFE"},
	{"signName":"GESTIN-KUR", "cuneiform":"gesztin-kur", "val":"\uD808\uDCFF"},
	{"signName":"LIMMU", "cuneiform":"limmu2", "val":"\uD808\uDDF9"},
	{"signName":"IA7", "cuneiform":"ia7", "val":"\uD809\uDC03"},
	{"signName":"AS4", "cuneiform":"asz4", "val":"\uD809\uDC04"},
	{"signName":"IMIN", "cuneiform":"imin2", "val":"\uD809\uDC05"},
	{"signName":"USSU", "cuneiform":"ussu2", "val":"\uD809\uDC06"},
	{"signName":"ILIMMU", "cuneiform":"ilimmu2", "val":"\uD809\uDC07"},
	{"signName":"TAG", "cuneiform":"SUM", "cuneiform1":"tag", "cuneiform2":"szum", "cuneiform3":"sub6", "cuneiform4":"tibir", "cuneiform5":"tuku5", "cuneiform6":"zil2", "val":"\uD808\uDEF3"},
	{"signName":"TAG-GU4", "cuneiform":"tag-gu4", "val":"\uD808\uDEF5"},
	{"signName":"TAG-SU", "cuneiform":"tag-szu", "val":"\uD808\uDEF7"},
	{"signName":"TAG-UD", "cuneiform":"tag-ud", "val":"\uD808\uDEF9"},
	{"signName":"TAG-TUG", "cuneiform":"tag-tug2", "val":"\uD808\uDEF8"},
	{"signName":"KA", "cuneiform":"ka2", "val":"\uD808\uDD8D"},
	{"signName":"AB", "cuneiform":"ab", "cuneiform1":"aba", "cuneiform2":"ap", "cuneiform3":"esz3", "cuneiform4":"is3", "val":"\uD808\uDC0A"},
	{"signName":"AB-KAR", "cuneiform":"ab-kar2", "val":"\uD808\uDC0E"},
	{"signName":"AB-SES", "cuneiform":"ab-szesz", "val":"\uD808\uDC13"},
	{"signName":"AB-AS", "cuneiform":"ab-azs", "val":"\uD808\uDC0B"},
	{"signName":"URUGAL", "cuneiform":"AB-GAL", "cuneiform1":"urugal", "cuneiform2":"ab-gal", "val":"\uD808\uDC0D"},
	{"signName":"AB-SIG7", "cuneiform":"ab-sig7", "val":"\uD808\uDC10"},
	{"signName":"URUDU", "cuneiform":"URUDA", "cuneiform1":"urudu", "cuneiform2":"uruda", "cuneiform3":"dab6", "val":"\uD808\uDF4F"},
	{"signName":"UNUG", "cuneiform":"AB-GUNU", "cuneiform1":"unug", "cuneiform2":"ab-gunu", "val":"\uD808\uDC15"},
	{"signName":"AB-LAGAB", "cuneiform":"ab-lagab", "val":"\uD808\uDC12"},
	{"signName":"AB-GIN", "cuneiform":"ab-gin2", "val":"\uD808\uDC0C"},
	{"signName":"NINA", "cuneiform":"AB-HA", "cuneiform1":"nina", "cuneiform2":"ab-ha", "val":"\uD808\uDC0F"},
	{"signName":"AB-IMIN", "cuneiform":"ab-imin", "val":"\uD808\uDC11"},
	{"signName":"UM", "cuneiform":"um", "cuneiform1":"dehi2", "val":"\uD808\uDF1D"},
	{"signName":"UM-U", "cuneiform":"um-u", "val":"\uD808\uDF21"},
	{"signName":"URUDU-U", "cuneiform":"urudu-u", "val":"\uD808\uDF50"},
	{"signName":"UM-ME-DA", "cuneiform":"um-me-da", "val":"\uD808\uDF1F"},
	{"signName":"DUB", "cuneiform":"dub", "val":"\uD808\uDC7E"},
	{"signName":"NAB", "cuneiform":"AN-AN", "cuneiform1":"nab", "cuneiform2":"an-an", "val":"\uD808\uDC2E"},
	{"signName":"MUL", "cuneiform":"AN-AN-AN", "cuneiform1":"mul", "cuneiform2":"an-an-an", "val":"\uD808\uDC2F"},
	{"signName":"TA", "cuneiform":"ta", "cuneiform1":"da2", "val":"\uD808\uDEEB"},
	{"signName":"TA*", "cuneiform":"ta*", "val":"\uD808\uDEEC"},
	{"signName":"TA-GUNU", "cuneiform":"ta-gunu", "val":"\uD808\uDEEF"},
	{"signName":"TA-HI", "cuneiform":"ta-hi", "val":"\uD808\uDEED"},
	{"signName":"TA-MI", "cuneiform":"ta-mi", "val":"\uD808\uDEEE"},
	{"signName":"I", "cuneiform":"i", "val":"\uD808\uDD3F"},
	{"signName":"GAN", "cuneiform":"gan", "cuneiform1":"gam4", "cuneiform2":"gana", "cuneiform3":"he2", "cuneiform4":"kan", "val":"\uD808\uDCF6"},
	{"signName":"TUR", "cuneiform":"tur", "cuneiform1":"ban3", "cuneiform2":"banda3", "cuneiform3":"di4", "cuneiform4":"dumu", "val":"\uD808\uDF09"},
	{"signName":"ZIZNA", "cuneiform":"zizna", "val":"\uD808\uDF0A"},
	{"signName":"AD", "cuneiform":"ad", "cuneiform1":"at", "val":"\uD808\uDC1C"},
	{"signName":"ZI", "cuneiform":"AB-PA", "cuneiform1":"zi2", "cuneiform2":"ab-pa", "cuneiform3":"ze2", "val":"\uD808\uDF62"},
	{"signName":"IA", "cuneiform":"ia", "val":"\uD808\uDD40"},
	{"signName":"IN", "cuneiform":"in", "cuneiform1":"en6", "cuneiform2":"isin2", "val":"\uD808\uDD54"},
	{"signName":"RAB", "cuneiform":"rab", "val":"\uD808\uDE90"},
	{"signName":"LUGAL", "cuneiform":"lugal", "cuneiform1":"lillan", "cuneiform2":"rab3", "cuneiform3":"szarrum", "val":"\uD808\uDE17"},
	{"signName":"LUGAL-LUGAL", "cuneiform":"lugal-lugal", "val":"\uD808\uDE18"},
	{"signName":"LUGAL-LUGAL*", "cuneiform":"lugal-lugal", "val":"\uD808\uDE19"},
	{"signName":"HASHUR", "cuneiform":"MA-GUNU", "cuneiform1":"haszhur", "val":"\uD808\uDE22"},
	{"signName":"EZEN", "cuneiform":"ezen", "cuneiform1":"asil", "cuneiform2":"ezem", "cuneiform3":"szer3", "cuneiform4":"szir3", "val":"\uD808\uDCA1"},
	{"signName":"KESDA", "cuneiform":"keszda", "cuneiform1":"kesz2", "cuneiform2":"gir11", "cuneiform3":"hir", "cuneiform4":"kesze2", "cuneiform5":"kirid", "val":"\uD808\uDD9F"},
	{"signName":"BAD3", "cuneiform":"UG5", "cuneiform1":"EZEN-BAD", "cuneiform2":"bad3", "cuneiform3":"ug5", "cuneiform4":"ezen-bad", "cuneiform5":"u9", "cuneiform6":"un3", "val":"\uD808\uDCA1"},
	{"signName":"UBARA", "cuneiform":"EZEN-KASKAL", "cuneiform1":"ubara", "cuneiform2":"ezen-kaskal", "cuneiform3":"un4", "val":"\uD808\uDCAC"},
	{"signName":"4UBARA", "cuneiform":"4ubara", "val":"\uD808\uDCAD"},
	{"signName":"EZEN-U", "cuneiform":"ezen-u2", "val":"\uD808\uDCB3"},
	{"signName":"EZEN-SIG7", "cuneiform":"ezen-sig7", "val":"\uD808\uDCAB"},
	{"signName":"EZEN-UD", "cuneiform":"ezen-ud", "val":"\uD808\uDCB4"},
	{"signName":"EZEN-KUG", "cuneiform":"ezen-kug", "val":"\uD808\uDCAE"},
	{"signName":"ASILAL", "cuneiform":"EZEN-LAL", "cuneiform1":"asilal", "cuneiform2":"ezen-lal2", "val":"\uD808\uDCB0"},
	{"signName":"EZEN-LU", "cuneiform":"ezen-lu", "val":"\uD808\uDCB2"},
	{"signName":"ASILAL3", "cuneiform":"EZEN-A", "cuneiform1":"asilal3", "cuneiform2":"ezen-a", "val":"\uD808\uDCA2"},
	{"signName":"SIL7", "cuneiform":"EZEN-A-LAL", "cuneiform1":"sil7", "cuneiform2":"ezen-a-lal", "val":"\uD808\uDCA3"},
	{"signName":"ASILAL4", "cuneiform":"EZEN-A-LAL2", "cuneiform1":"asilal4", "cuneiform2":"ezen-a-lal2", "val":"\uD808\uDCA4"},
	{"signName":"EZEN-HA", "cuneiform":"ezen-ha", "val":"\uD808\uDCA9"},
	{"signName":"SUM", "cuneiform":"sum", "cuneiform1":"si3", "cuneiform2":"sig10", "cuneiform3":"szum2", "val":"\uD808\uDEE7"},
	{"signName":"NAGA", "cuneiform":"naga", "val":"\uD808\uDE40"},
	{"signName":"4AN-NAGA", "cuneiform":"4an-naga", "val":"\uD808\uDC31"},
	{"signName":"NAGA*", "cuneiform":"naga*", "val":"\uD808\uDE41"},
	{"signName":"NAGA-SU-TENU", "cuneiform":"naga-szu-tenu", "val":"\uD808\uDE42"},
	{"signName":"NIB", "cuneiform":"PIRIG-KAL", "cuneiform1":"nib", "cuneiform2":"pirig-kal", "val":"\uD808\uDE8B"},
	{"signName":"UG", "cuneiform":"PIRIG-UD", "cuneiform1":"ug", "cuneiform2":"pirig-ud", "val":"\uD808\uDE8C"},
	{"signName":"AZ", "cuneiform":"PIRIG-ZA", "cuneiform1":"az", "cuneiform2":"pirig-za", "val":"\uD808\uDE8D"},
	{"signName":"DUH", "cuneiform":"duh", "val":"\uD808\uDC83"},
	{"signName":"GABA", "cuneiform":"gaba", "cuneiform1":"du8", "cuneiform2":"duh", "cuneiform3":"gab", "val":"\uD808\uDCEE"},
	{"signName":"EDIN", "cuneiform":"edin", "cuneiform1":"bir4", "cuneiform2":"ru6", "val":"\uD808\uDC94"},
	{"signName":"TAH", "cuneiform":"DAH", "cuneiform1":"MU-MU", "cuneiform2":"tah", "cuneiform3":"dah", "cuneiform4":"mu-mu", "val":"\uD808\uDE2D"},
	{"signName":"KASKAL", "cuneiform":"kaskal", "cuneiform1":"esz8", "cuneiform2":"ir7", "cuneiform3":"rasz", "val":"\uD808\uDD9C"},
	{"signName":"KASKAL-TUL-TUL", "cuneiform":"kaskal-tul-tul", "val":"\uD808\uDD9D"},
	{"signName":"AM", "cuneiform":"GU4-KUR", "cuneiform1":"am", "cuneiform2":"gu4-kur", "cuneiform3":"gud-kur", "cuneiform4":"ildag3", "val":"\uD808\uDD20"},
	{"signName":"UZU", "cuneiform":"uzu", "val":"\uD808\uDF5C"},
	{"signName":"BIL", "cuneiform":"GIBIL", "cuneiform1":"NE-PAB", "cuneiform2":"NE-SESSIG", "cuneiform3":"bil2", "cuneiform4":"gibil", "cuneiform5":"ne-pab", "cuneiform6":"ne-szeszszig", "val":"\uD808\uDE4B"},
	{"signName":"pil", "cuneiform":"ne", "cuneiform1":"bar7", "cuneiform2":"be7", "cuneiform3":"bi2", "cuneiform4":"de3", "cuneiform5":"bil", "cuneiform6":"izi", "cuneiform7":"lam2", "val":"\uD808\uDE48"},
	{"signName":"EMES", "cuneiform":"NE-UD", "cuneiform1":"emesz2", "cuneiform2":"ne-ud", "val":"\uD808\uDE4A"},
	{"signName":"ENTEN", "cuneiform":"NE-A", "cuneiform1":"enten", "cuneiform2":"ne-a", "val":"\uD808\uDE49"},
	{"signName":"NINDA", "cuneiform":"ninda2", "val":"\uD808\uDE52"},
	{"signName":"NINDA-AS", "cuneiform":"ninda2-asz", "val":"\uD808\uDE54"},
	{"signName":"NINDA-AS-AS", "cuneiform":"ninda2-asz-asz", "val":"\uD808\uDE55"},
	{"signName":"SAM3", "cuneiform":"NINDA-AN", "cuneiform1":"szam3", "cuneiform2":"ninda2-an", "val":"\uD808\uDE53"},
	{"signName":"SUMAS", "cuneiform":"sumasz", "val":"\uD808\uDEE8"},
	{"signName":"AZU", "cuneiform":"NINDA-NUN", "cuneiform1":"azu", "cuneiform2":"ninda2-nun", "val":"\uD808\uDE59"},
	{"signName":"ZU5", "cuneiform":"zu5", "val":"\uD808\uDF6B"},
	{"signName":"AZU-A", "cuneiform":"azu-a", "val":"\uD808\uDF6C"},
	{"signName":"AG", "cuneiform":"NINDA-NE", "cuneiform1":"ag2", "cuneiform2":"ninda2-ne", "cuneiform3":"eg3", "cuneiform4":"em3", "cuneiform5":"ig3", "val":"\uD808\uDE58"},
	{"signName":"NINDA-GU4", "cuneiform":"ninda2-gu4", "val":"\uD808\uDE56"},
	{"signName":"NINDA-U-AS", "cuneiform":"ninda2-u2-asz", "val":"\uD808\uDE5E"},
	{"signName":"NINDA-SE-AS", "cuneiform":"ninda2-sze-asz", "val":"\uD808\uDE5C"},
	{"signName":"NINDA-SE-AS-AS", "cuneiform":"ninda2-sze-asz-asz", "val":"\uD808\uDE5D"},
	{"signName":"NINDA-SE", "cuneiform":"ninda2-sze", "cuneiform1":"sa10", "cuneiform2":"sam2", "cuneiform3":"szam2", "val":"\uD808\uDE5A"},
	{"signName":"NINDA-SE-A-AN", "cuneiform":"ninda2-sze-a-an", "val":"\uD808\uDE5B"},
	{"signName":"ZIG", "cuneiform":"ZIK", "cuneiform1":"NINDA-ES", "cuneiform2":"zig", "cuneiform3":"zik", "cuneiform4":"ninda2-esz", "cuneiform5":"hasz2", "cuneiform6":"zib2", "val":"\uD808\uDF68"},
	{"signName":"NINDA-ME-KAR", "cuneiform":"ninda2-me-kar2", "val":"\uD808\uDE57"},
	{"signName":"GALAM", "cuneiform":"SUKUD", "cuneiform1":"galam", "cuneiform2":"sukud", "val":"\uD808\uDCF4"},
	{"signName":"KUM", "cuneiform":"GUM", "cuneiform1":"kum", "cuneiform2":"gum", "cuneiform3":"naga4", "cuneiform4":"qum", "val":"\uD808\uDD23"},
	{"signName":"GAZ", "cuneiform":"KUM-SE", "cuneiform1":"gaz", "cuneiform2":"kum-sze", "val":"\uD808\uDD24"},
	{"signName":"UR", "cuneiform":"ur2", "val":"\uD808\uDF2B"},
	{"signName":"UR-NUN", "cuneiform":"ur2-nun", "val":"\uD808\uDF30"},
	{"signName":"UR-AL", "cuneiform":"ur2-al", "val":"\uD808\uDF2E"},
	{"signName":"UR-U", "cuneiform":"ur2-u2", "val":"\uD808\uDF31"},
	{"signName":"UR-U-AS", "cuneiform":"ur2-u2-asz", "val":"\uD808\uDF32"},
	{"signName":"UR-A-HA", "cuneiform":"ur2-a-ha", "val":"\uD808\uDF2C"},
	{"signName":"UR-HA", "cuneiform":"ur2-ha", "val":"\uD808\uDF2F"},
	{"signName":"IL", "cuneiform":"AL-SE", "cuneiform1":"il", "cuneiform2":"al-sze",  "val":"\uD808\uDD4B"},
	{"signName":"IL-KAR", "cuneiform":"il-kar2", "val":"\uD808\uDD4C"},
	{"signName":"DU", "cuneiform":"du", "val":"\uD808\uDC7A"},
	{"signName":"LAH4", "cuneiform":"DU-DU", "cuneiform1":"lah4", "cuneiform2":"du-du", "cuneiform3":"re7", "cuneiform4":"su8", "cuneiform5":"sub2", "cuneiform6":"sug2", "val":"\uD808\uDC7B"},
	{"signName":"SUHUS", "cuneiform":"DU-GUNU", "cuneiform1":"suhusz", "cuneiform2":"du-gunu",  "val":"\uD808\uDC7C"},
	{"signName":"KAS4", "cuneiform":"DU-SESSIG", "cuneiform1":"kasz4", "cuneiform2":"du-szeszszig", "cuneiform3":"gir5", "cuneiform4":"im2", "cuneiform5":"rim4", "val":"\uD808\uDC7D"},
	{"signName":"ANSE", "cuneiform":"GIR3-TAB", "cuneiform1":"ansze", "cuneiform2":"gir3-tab",  "val":"\uD808\uDC32"},
	{"signName":"GIR3-PA", "cuneiform":"gir3-pa", "val":"\uD808\uDD0F"},
	{"signName":"TUM", "cuneiform":"tum", "cuneiform1":"dum", "cuneiform2":"eb2", "cuneiform3":"ib2", "val":"\uD808\uDF08"},
	{"signName":"EGIR", "cuneiform":"egir", "val":"\uD808\uDC95"},
	{"signName":"IS", "cuneiform":"isz", "cuneiform1":"isisz", "cuneiform2":"iszi", "cuneiform3":"kusz7", "cuneiform4":"kukkusz", "cuneiform5":"sahar", "val":"\uD808\uDD56"},
	{"signName":"BI", "cuneiform":"bi", "cuneiform1":"be2", "cuneiform2":"biz", "cuneiform3":"kasz", "cuneiform4":"pe2", "cuneiform5":"pi2", "val":"\uD808\uDC49"},
	{"signName":"ESEMIN5", "cuneiform":"eszemin5", "val":"\uD809\uDC59"},
	{"signName":"BI-SIG7", "cuneiform":"bi-sig7", "val":"\uD808\uDC4C"},
	{"signName":"BI-GAR", "cuneiform":"bi-gar", "val":"\uD808\uDC4B"},
	{"signName":"SIM", "cuneiform":"szim", "cuneiform1":"bappir2", "cuneiform2":"lunga", "cuneiform3":"mud5", "cuneiform4":"szem", "cuneiform5":"szembi2", "cuneiform6":"szembizid", "val":"\uD808\uDEC6"},
	{"signName":"SIM-BAL", "cuneiform":"szim-bal", "val":"\uD808\uDEC8"},
	{"signName":"SIM-MUG", "cuneiform":"szim-mug", "val":"\uD808\uDED0"},
	{"signName":"SIM-DIN", "cuneiform":"szim-din", "val":"\uD808\uDECA"},
	{"signName":"SIM-BULUG", "cuneiform":"szim-bulug", "val":"\uD808\uDEC9"},
	{"signName":"SIM-SIG7", "cuneiform":"szim-sig7", "val":"\uD808\uDECD"},
	{"signName":"SIM-LUL", "cuneiform":"szim-lul", "val":"\uD808\uDECF"},
	{"signName":"SIM-IGI", "cuneiform":"szim-igi", "val":"\uD808\uDECC"},
	{"signName":"SIM-A", "cuneiform":"DUMGAL", "cuneiform1":"szim-a", "cuneiform2":"dumgal",  "val":"\uD808\uDEC7"},
	{"signName":"SIM-NIG", "cuneiform":"BAPPIR", "cuneiform1":"szim-nig2", "cuneiform2":"bappir",  "val":"\uD808\uDECB"},
	{"signName":"SIM-MUNUS", "cuneiform":"SIM-SAL", "cuneiform1":"szim-munus", "cuneiform2":"szim-sal",  "val":"\uD808\uDED1"},
	{"signName":"SIM-KUSU", "cuneiform":"szim-kuszu2", "val":"\uD808\uDECE"},
	{"signName":"GISAL", "cuneiform":"BI-GIS", "cuneiform1":"gisal", "cuneiform2":"bi-gisz",  "val":"\uD808\uDD10"},
	{"signName":"BANSUR", "cuneiform":"banszur2", "val":"\uD808\uDD43"},
	{"signName":"GAN-GAN", "cuneiform":"gan2-gan2", "cuneiform1":"ulul2", "val":"\uD808\uDCFA"},
	{"signName":"GIS-GIS", "cuneiform":"gisz-gisz", "cuneiform1":"hul3", "cuneiform2":"lirum3", "cuneiform3":"szennur", "cuneiform4":"ul3", "cuneiform5":"kib", "val":"\uD808\uDC12"},
	{"signName":"GAG", "cuneiform":"KAK", "cuneiform1":"gag", "cuneiform2":"kak", "cuneiform3":"da3", "cuneiform4":"du3", "cuneiform5":"henbur", "cuneiform6":"ru2", "val":"\uD808\uDD95"},
	{"signName":"ne2", "cuneiform":"ni", "cuneiform1":"be3", "cuneiform2":"dig", "cuneiform3":"i3", "cuneiform4":"ia3", "cuneiform5":"le2", "cuneiform6":"zal", "cuneiform7":"susz2", "val":"\uD808\uDE4C"},
	{"signName":"NI-E", "cuneiform":"ni-e", "val":"\uD808\uDE4D"},
	{"signName":"US", "cuneiform":"NITA", "cuneiform1":"usz", "cuneiform2":"nita", "cuneiform3":"gisz3", "cuneiform4":"nitah", "cuneiform5":"us2", "val":"\uD808\uDF51"},
	{"signName":"US-KID", "cuneiform":"usz-kid2", "val":"\uD808\uDF55"},
	{"signName":"US-KU", "cuneiform":"usz-ku", "val":"\uD808\uDF53"},
	{"signName":"KAS3", "cuneiform":"US-A", "cuneiform1":"kasz3", "cuneiform2":"usz-a",  "val":"\uD808\uDF52"},
	{"signName":"GA", "cuneiform":"MAL", "cuneiform1":"ga2", "cuneiform2":"mal", "cuneiform3":"ba4", "cuneiform4":"ge26", "cuneiform5":"ma3", "cuneiform6":"pisag", "val":"\uD808\uDCB7"},
	{"signName":"SITA", "cuneiform":"szita", "val":"\uD808\uDED6"},
	{"signName":"GA-AS", "cuneiform":"ga2-asz", "val":"\uD808\uDCBD"},
	{"signName":"GA-HAL-LA", "cuneiform":"ga2-hal-la", "val":"\uD808\uDCD3"},
	{"signName":"GA-GIR-SU", "cuneiform":"ga2-gir2-su", "val":"\uD808\uDCD0"},
	{"signName":"AMA", "cuneiform":"GA-AN", "cuneiform1":"ama", "cuneiform2":"ga2-an", "cuneiform3":"dagal", "val":"\uD808\uDCBC"},
	{"signName":"GA-KID", "cuneiform":"ga2-kid2", "val":"\uD808\uDCE9"},
	{"signName":"GA-BAD", "cuneiform":"ga2-bad", "val":"\uD808\uDCBF"},
	{"signName":"GA-GI", "cuneiform":"ga2-gi", "val":"\uD808\uDCCD"},
	{"signName":"GANUN", "cuneiform":"GA-NUN", "cuneiform1":"ga2-nun", "cuneiform2":"ganun",  "val":"\uD808\uDCE0"},
	{"signName":"GA-KAB", "cuneiform":"ga2-kab", "val":"\uD808\uDCD5"},
	{"signName":"GA-EN", "cuneiform":"ga2-en", "val":"\uD808\uDCC9"},
	{"signName":"GA-BURU14", "cuneiform":"ga2-buru14", "val":"\uD808\uDCCA"},
	{"signName":"GA-MUN", "cuneiform":"DIM-KUR", "cuneiform1":"ga2-mun", "cuneiform2":"dim-kur",  "val":"\uD808\uDCC5"},
	{"signName":"GA-KAR", "cuneiform":"ga2-kar2","val":"\uD808\uDCCB"},
	{"signName":"GA-DUB", "cuneiform":"ga2-dub", "val":"\uD808\uDCC6"},
	{"signName":"GA-SUM", "cuneiform":"ga2-sum", "val":"\uD808\uDCE8"},
	{"signName":"GA-KASKAL", "cuneiform":"ga2-kaskal", "val":"\uD808\uDCD9"},
	{"signName":"GA-IS-HU-AS", "cuneiform":"ga2-isz-hu-asz", "val":"\uD808\uDCD7"},
	{"signName":"GA-GAG", "cuneiform":"ga2-gag", "val":"\uD808\uDCD8"},
	{"signName":"SILA4", "cuneiform":"GA-PA", "cuneiform1":"sila4", "cuneiform2":"ga2-pa", "cuneiform3":"gazi", "val":"\uD808\uDCE2"},
	{"signName":"GA-KID-LAL", "cuneiform":"ga2-kid-lal", "val":"\uD808\uDCDB"},
	{"signName":"GA-SID", "cuneiform":"ga2-szid", "val":"\uD808\uDCE7"},
	{"signName":"UR3", "cuneiform":"GA-NIR", "cuneiform1":"ur3", "cuneiform2":"ga2-nir",  "val":"\uD808\uDCE1"},
	{"signName":"GA-GI4", "cuneiform":"ga2-gi4", "val":"\uD808\uDCCE"},
	{"signName":"GA-SAR", "cuneiform":"ga2-sar", "val":"\uD808\uDCE4"},
	{"signName":"GA-AS-GAL", "cuneiform":"ga2-asz2-gal", "val":"\uD808\uDCBE"},
	{"signName":"GA-BUR-RA", "cuneiform":"ga2-bur-ra", "val":"\uD808\uDCC2"},
	{"signName":"GA-DA", "cuneiform":"ga2-da", "val":"\uD808\uDCC3"},
	{"signName":"GA-SIG7", "cuneiform":"ga2-sig7", "val":"\uD808\uDCD6"},
	{"signName":"ESAG", "cuneiform":"GA-SE", "cuneiform1":"ga2-sze", "cuneiform2":"esag2",  "val":"\uD808\uDCE5"},
	{"signName":"E-SE", "cuneiform":"e2-sze", "val":"\uD808\uDC92"},
	{"signName":"GA-SE-TUR", "cuneiform":"ga2-sze-tur", "val":"\uD808\uDCE6"},
	{"signName":"GA-UD", "cuneiform":"ga2-ud", "val":"\uD808\uDCEB"},
	{"signName":"GA-HI-LI", "cuneiform":"ga2-hi-li", "val":"\uD808\uDCD4"},
	{"signName":"GA-U", "cuneiform":"ga2-u", "val":"\uD808\uDCEA"},
	{"signName":"ITIMA", "cuneiform":"GA-MI", "cuneiform1":"itima", "cuneiform2":"ga2-mi",  "val":"\uD808\uDCDF"},
	{"signName":"E-MI", "cuneiform":"e2-mi", "val":"\uD808\uDC90"},
	{"signName":"GA-DI", "cuneiform":"ga2-di", "val":"\uD808\uDCC4"},
	{"signName":"GA-KUG-AN", "cuneiform":"ga2-kug-an", "val":"\uD808\uDCDC"},
	{"signName":"MEN", "cuneiform":"GA-ME-EN", "cuneiform1":"men", "cuneiform2":"ga2-me-en", "cuneiform3":"dan2", "val":"\uD808\uDCDE"},
	{"signName":"GA-A-DA-HA", "cuneiform":"ga2-a-da-ha", "cuneiform1":"E-A-DA-HA", "cuneiform2":"e2-a-da-ha","val":"\uD808\uDCB8"},
	{"signName":"GA-A-IGI", "cuneiform":"ga2-a-igi", "val":"\uD808\uDCBA"},
	{"signName":"GA-HA-LU-SE", "cuneiform":"ga2-ha-lu-sze", "val":"\uD808\uDCD1"},
	{"signName":"GALGA", "cuneiform":"GA-NIG", "cuneiform1":"galga", "cuneiform2":"ga2-nig2",  "val":"\uD808\uDCCC"},
	{"signName":"E-NIG", "cuneiform":"e2-nig2", "val":"\uD808\uDC8F"},
	{"signName":"ARHUS", "cuneiform":"GA-MUNUS", "cuneiform1":"arhusz", "cuneiform2":"ga2-munus", "cuneiform3":"ama5", "cuneiform4":"ga2-sal", "val":"\uD808\uDCE3"},
	{"signName":"E-MUNUS", "cuneiform":"e2-munus", "val":"\uD808\uDC91"},
	{"signName":"GA-EL-LA", "cuneiform":"ga2-el-la", "val":"\uD808\uDCC8"},
	{"signName":"KISAL", "cuneiform":"kisal", "cuneiform1":"par4", "val":"\uD808\uDDA6"},
	{"signName":"IR", "cuneiform":"GAG-GUNU", "cuneiform1":"ir", "cuneiform2":"gag-gunu", "cuneiform3":"er", "val":"\uD808\uDD55"},
	{"signName":"DAG", "cuneiform":"PAR3", "cuneiform1":"dag", "cuneiform2":"par3", "cuneiform3":"tag2", "cuneiform4":"par3", "val":"\uD808\uDC56"},
	{"signName":"KISI8", "cuneiform":"DAG-KISIM5-GIR", "cuneiform1":"kiszi8", "cuneiform2":"dag-kisim5-gir2",  "val":"\uD808\uDC5E"},
	{"signName":"DAG-KISIM5-LA", "cuneiform":"dag-kisim5-la", "val":"\uD808\uDC64"},
	{"signName":"DAG-KISIM5-MUNU4", "cuneiform":"dag-kisim5-munu4", "val":"\uD808\uDC69"},
	{"signName":"DAG-KISIM5-KID", "cuneiform":"dag-kisim5-kid2", "val":"\uD808\uDC6B"},
	{"signName":"DAG-KISIM5-GI", "cuneiform":"dag-kisim5-gi", "val":"\uD808\uDC5D"},
	{"signName":"DAG-KISIM5-SI", "cuneiform":"dag-kisim5-si", "val":"\uD808\uDC6A"},
	{"signName":"DAG-KISIM5-NE", "cuneiform":"dag-kisim5-ne", "val":"\uD808\uDC68"},
	{"signName":"DAG-KISIM5-BI", "cuneiform":"dag-kisim5-bi", "val":"\uD808\uDC5A"},
	{"signName":"DAG-KISIM5-GAG", "cuneiform":"dag-kisim5-gag", "val":"\uD808\uDC63"},
	{"signName":"UTUA", "cuneiform":"DAG-KISIM5-US", "cuneiform1":"utua", "cuneiform2":"dag-kisim5-usz","val":"\uD808\uDC6D"},
	{"signName":"UBUR3", "cuneiform":"DAG-KISIM5-IR", "cuneiform1":"ubur3", "cuneiform2":"dag-kisim5-ir","val":"\uD808\uDC61"},
	{"signName":"UBUR4", "cuneiform":"DAG-KISIM5-IR-LU", "cuneiform1":"ubur4", "cuneiform2":"dag-kisim5-il-lu","val":"\uD808\uDC62"},
	{"signName":"UTUL5", "cuneiform":"DAG-KISIM5-GU4", "cuneiform1":"utul5", "cuneiform2":"dag-kisim5-gu4","val":"\uD808\uDC5F"},
	{"signName":"KISI9", "cuneiform":"DAG-KISIM5-U-GIR", "cuneiform1":"kiszi9", "cuneiform2":"dag-kisim5-u2-gir2","val":"\uD808\uDC6C"},
	{"signName":"UBUR", "cuneiform":"DAG-KISIM5-GA", "cuneiform1":"ubur", "cuneiform2":"dag-kisim5-ga","val":"\uD808\uDC5B"},
	{"signName":"DAG-KISIM5-DUB", "cuneiform":"DAG-KISIM5-BALAG", "cuneiform1":"dag-kisim5-dub2", "cuneiform2":"dag-kisim5-balag","val":"\uD808\uDC59"},
	{"signName":"DAG-KISIM5-AMAR", "cuneiform":"dag-kisim5-amar", "val":"\uD808\uDC58"},
	{"signName":"UBUR", "cuneiform":"DAG-KISIM5-LU", "cuneiform1":"ubur2", "cuneiform2":"dag-kisim5-lu","val":"\uD808\uDC65"},
	{"signName":"AMAS", "cuneiform":"DAG-KISIM5-LU-MAS", "cuneiform1":"amasz", "cuneiform2":"dag-kisim5-lu-masz2","val":"\uD808\uDC66"},
	{"signName":"DAG-KISIM5-A-MAS", "cuneiform":"dag-kisim5-a-masz", "val":"\uD808\uDC57"},
	{"signName":"DAG-KISIM5-HA", "cuneiform":"dag-kisim5-ha", "val":"\uD808\uDC60"},
	{"signName":"DAG-KISIM5-LUM", "cuneiform":"dag-kisim5-lum", "val":"\uD808\uDC67"},
	{"signName":"hendur", "cuneiform":"pa", "cuneiform1":"kun2", "cuneiform2":"mu6", "cuneiform3":"mudru", "cuneiform4":"sag3", "cuneiform5":"sig3", "cuneiform6":"ugula", "cuneiform7":"gidru", "val":"\uD808\uDE7A"},
	{"signName":"BANMIN", "cuneiform":"banmin", "val":"\uD809\uDC50"},
	{"signName":"GIS", "cuneiform":"GES", "cuneiform1":"gisz", "cuneiform2":"gesz", "cuneiform3":"is", "cuneiform4":"isz6", "cuneiform5":"iz", "val":"\uD808\uDD11"},
	{"signName":"GIS-TENU", "cuneiform":"gisz-tenu", "val":"\uD808\uDD15"},
	{"signName":"GIS-BAD", "cuneiform":"gisz-bad", "val":"\uD808\uDD13"},
	{"signName":"GU4", "cuneiform":"GUD", "cuneiform1":"gu4", "cuneiform2":"gud","val":"\uD808\uDD1E"},
	{"signName":"AL", "cuneiform":"al", "val":"\uD808\uDC20"},
	{"signName":"AL-KAD3", "cuneiform":"al-kad3", "val":"\uD808\uDC25"},
	{"signName":"AL-US", "cuneiform":"al-usz", "val":"\uD808\uDC28"},
	{"signName":"AL-GIS", "cuneiform":"al-gisz", "val":"\uD808\uDC23"},
	{"signName":"AL-AL", "cuneiform":"al-al", "val":"\uD808\uDC21"},
	{"signName":"AL-SE", "cuneiform":"al-sze", "val":"\uD808\uDC27"},
	{"signName":"AL-GIM", "cuneiform":"al-gim", "val":"\uD808\uDC22"},
	{"signName":"AL-KI", "cuneiform":"al-ki", "val":"\uD808\uDC26"},
	{"signName":"AL-HA", "cuneiform":"al-ha", "val":"\uD808\uDC24"},
	{"signName":"MAR", "cuneiform":"mar", "val":"\uD808\uDE25"},
	{"signName":"KID", "cuneiform":"LIL", "cuneiform1":"kid", "cuneiform2":"lil2", "cuneiform3":"ge2", "cuneiform4":"gi2", "cuneiform5":"ke4", "val":"\uD808\uDDA4"},
	{"signName":"nesag2", "cuneiform":"pisag2", "cuneiform1":"szid", "cuneiform2":"lag", "cuneiform3":"kas7", "cuneiform4":"kiri8", "cuneiform5":"sag5", "cuneiform6":"szub6", "cuneiform7":"szudum", "val":"\uD808\uDEC3"},
	{"signName":"SAG5", "cuneiform":"sag5", "val":"\uD808\uDE60"},
	{"signName":"MES", "cuneiform":"RID", "cuneiform1":"mes", "cuneiform2":"rid", "cuneiform3":"kiszib", "cuneiform4":"mesz3", "val":"\uD808\uDE29"},
	{"signName":"SID-IM", "cuneiform":"szid-im", "val":"\uD808\uDEC5"},
	{"signName":"UMBISAG", "cuneiform":"SID-A", "cuneiform1":"umbisag2", "cuneiform2":"szid-a", "cuneiform3":"alal", "cuneiform4":"pisag3", "val":"\uD808\uDEC4"},
	{"signName":"U", "cuneiform":"u2", "cuneiform1":"kusz3", "val":"\uD808\uDF11"},
	{"signName":"GA", "cuneiform":"ga", "cuneiform1":"gur11", "cuneiform2":"ka3", "cuneiform3":"qa2", "val":"\uD808\uDCB5"},
	{"signName":"GA-GUNU", "cuneiform":"ga-gunu", "cuneiform1":"gara2", "val":"\uD808\uDCB6"},
	{"signName":"IL", "cuneiform":"GA-GIN", "cuneiform1":"il2", "cuneiform2":"ga-gin2", "cuneiform3":"dusu", "cuneiform4":"ga6", "cuneiform5":"gur3", "cuneiform6":"guru3", "val":"\uD808\uDD4D"},
	{"signName":"LUH", "cuneiform":"luh", "cuneiform1":"huluh", "cuneiform2":"sukkal", "val":"\uD808\uDE1B"},
	{"signName":"E", "cuneiform":"e2", "val":"\uD808\uDC8D"},
	{"signName":"zi8", "cuneiform":"kal", "cuneiform1":"alad2", "cuneiform2":"esi", "cuneiform3":"gurusz", "cuneiform4":"kalag", "cuneiform5":"lamma", "cuneiform6":"rib", "cuneiform7":"sun7", "val":"\uD808\uDD97"},
	{"signName":"GURUS", "cuneiform":"gurusz", "val":"\uD808\uDD28"},
	{"signName":"KAL-KAL", "cuneiform":"kal-kal", "val":"\uD808\uDD99"},
	{"signName":"ALAD", "cuneiform":"KAL-BAD", "cuneiform1":"alad", "cuneiform2":"kal-bad","val":"\uD808\uDD98"},
	{"signName":"E", "cuneiform":"e", "cuneiform1":"eg2", "val":"\uD808\uDC8A"},
	{"signName":"E-E-NUN-NUN", "cuneiform":"e-e-nun-nun", "val":"\uD808\uDC8C"},
	{"signName":"DUG", "cuneiform":"dug", "cuneiform1":"epir", "cuneiform2":"gurun7", "cuneiform3":"kurin", "cuneiform4":"kurun3", "val":"\uD808\uDC81"},
	{"signName":"BI-A", "cuneiform":"bi-a", "val":"\uD808\uDC4A"},
	{"signName":"KALAM", "cuneiform":"kalam", "val":"\uD808\uDF26"},
	{"signName":"UN", "cuneiform":"un", "cuneiform1":"kalam", "cuneiform2":"ug3", "val":"\uD808\uDF27"},
	{"signName":"NIR", "cuneiform":"NUN-NUN", "cuneiform1":"nir", "cuneiform2":"nun-nun","val":"\uD808\uDE6A"},
	{"signName":"GURUN", "cuneiform":"gurun", "val":"\uD808\uDD27"},
	{"signName":"UB", "cuneiform":"ub", "cuneiform1":"ar2", "cuneiform2":"up", "val":"\uD808\uDF12"},
	{"signName":"ES16", "cuneiform":"AS-AS-AS", "cuneiform1":"esz16", "cuneiform2":"asz-asz-asz","val":"\uD808\uDC3C"},
	{"signName":"LIMMU4", "cuneiform":"limmu4", "val":"\uD809\uDC3D"},
	{"signName":"GI4", "cuneiform":"GI-GUNU", "cuneiform1":"gi4", "cuneiform2":"gi-gunu", "cuneiform3":"ge4", "cuneiform4":"qi4", "val":"\uD808\uDD04"},
	{"signName":"GIGI", "cuneiform":"gigi", "val":"\uD808\uDD06"},
	{"signName":"GI4-GI4", "cuneiform":"gi4-gi4", "val":"\uD808\uDD05"},
	{"signName":"USAN", "cuneiform":"GU-GUNU", "cuneiform1":"usan2", "cuneiform2":"gu2-gunu","val":"\uD808\uDD1D"},
	{"signName":"RA", "cuneiform":"ra", "val":"\uD808\uDE8F"},
	{"signName":"DUL3", "cuneiform":"SAG-GUNU", "cuneiform1":"dul3", "cuneiform2":"sag-gunu", "cuneiform3":"kusz2", "cuneiform4":"kuszu4", "cuneiform5":"sumur", "cuneiform6":"sur2", "val":"\uD808\uDEA8"},
	{"signName":"LU", "cuneiform":"lu2", "val":"\uD808\uDDFD"},
	{"signName":"LU-LU", "cuneiform":"lu2-lu2", "val":"\uD808\uDE12"},
	{"signName":"LU-LU*", "cuneiform":"lu2-lu2*", "val":"\uD808\uDE13"},
	{"signName":"4-LU", "cuneiform":"4-lu2", "val":"\uD808\uDE14"},
	{"signName":"LU-TENU", "cuneiform":"lu2-tenu", "val":"\uD808\uDE11"},
	{"signName":"LU-SESSIG", "cuneiform":"LU-GAM", "cuneiform1":"lu2-szeszszig", "cuneiform2":"lu2-gam", "cuneiform3":"ri9", "val":"\uD808\uDE15"},
	{"signName":"LU-BAD", "cuneiform":"lu2-bad", "cuneiform1":"ad6", "val":"\uD808\uDDFF"},
	{"signName":"LU-KAD", "cuneiform":"lu2-kad2", "val":"\uD808\uDE05"},
	{"signName":"LU-KID", "cuneiform":"LU-KAD3", "cuneiform1":"lu2-kid2", "cuneiform2":"lu2-kad3","val":"\uD808\uDE06"},
	{"signName":"LU-KAR", "cuneiform":"LU-GAN-TENU", "cuneiform1":"lu2-kar2", "cuneiform2":"lu2-gan2-tenu", "cuneiform3":"szaga", "cuneiform4":"sze29", "val":"\uD808\uDE02"},
	{"signName":"LU-NE", "cuneiform":"lu2-ne", "cuneiform1":"du14", "val":"\uD808\uDE0C"},
	{"signName":"LU-AL", "cuneiform":"lu2-al", "val":"\uD808\uDDFE"},
	{"signName":"LU-KAM", "cuneiform":"lu2-kam", "val":"\uD808\uDE03"},
	{"signName":"LU-IM", "cuneiform":"lu2-im", "val":"\uD808\uDE04"},
	{"signName":"LU-KI", "cuneiform":"lu2-ki", "val":"\uD808\uDE08"},
	{"signName":"LU-ME-EN", "cuneiform":"lu2-me-en", "val":"\uD808\uDE0B"},
	{"signName":"LU-LAGAB", "cuneiform":"lu2-lagab", "val":"\uD808\uDE0A"},
	{"signName":"LU-TUG", "cuneiform":"lu2-tug2", "val":"\uD808\uDE10"},
	{"signName":"LU-SE3", "cuneiform":"lu2-sze3", "val":"\uD808\uDE00"},
	{"signName":"LU-SE3-TENU", "cuneiform":"lu2-sze3-tenu", "val":"\uD808\uDE01"},
	{"signName":"LU-SIG-BU", "cuneiform":"lu2-sig2-bu", "val":"\uD808\uDE0F"},
	{"signName":"SES", "cuneiform":"szesz", "cuneiform1":"mun4", "cuneiform2":"musz5", "cuneiform3":"sis", "val":"\uD808\uDEC0"},
	{"signName":"URI3", "cuneiform":"uri3", "val":"\uD808\uDF36"},
	{"signName":"AS9", "cuneiform":"ES16-ES16", "cuneiform1":"asz9", "cuneiform2":"esz16-esz16","val":"\uD809\uDC40"},
	{"signName":"IMIN3", "cuneiform":"ES16-ES16-AS", "cuneiform1":"imin3", "cuneiform2":"esz16-esz16-asz","val":"\uD809\uDC41"},
	{"signName":"USSU3", "cuneiform":"ES16-ES16-TAB", "cuneiform1":"ussu3", "cuneiform2":"esz16-esz16-tab","val":"\uD809\uDC45"},
	{"signName":"ILIMMU3", "cuneiform":"ES16-ES16-ES16", "cuneiform1":"ilimmu3", "cuneiform2":"esz16-esz16-esz16","val":"\uD809\uDC47"},
	{"signName":"ZAG", "cuneiform":"zag", "cuneiform1":"za3", "cuneiform2":"zak", "val":"\uD808\uDF60"},
	{"signName":"SAR", "cuneiform":"sar", "val":"\uD808\uDEAC"},
	{"signName":"UD-GUNU", "cuneiform":"ud-gunu", "val":"\uD808\uDF19"},
	{"signName":"GAR3", "cuneiform":"QAR", "cuneiform1":"gar3", "cuneiform2":"qar", "cuneiform3":"gara3", "val":"\uD808\uDCFC"},
	{"signName":"LIL", "cuneiform":"lil", "val":"\uD808\uDDF8"},
	{"signName":"MURU", "cuneiform":"MURUB4", "cuneiform1":"NISAG", "cuneiform2":"ITI-GUNU", "cuneiform3":"muru2", "cuneiform4":"murub4", "cuneiform5":"nisag", "cuneiform6":"iti-gunu","val":"\uD808\uDF18"},
	{"signName":"DE", "cuneiform":"SIMUG", "cuneiform1":"UMUM", "cuneiform2":"de2", "cuneiform3":"simug", "cuneiform4":"umum", "val":"\uD808\uDF23"},
	{"signName":"DE-KASKAL", "cuneiform":"de2-kaskal","val":"\uD808\uDF24"},
	{"signName":"DE-PA", "cuneiform":"de2-pa", "val":"\uD808\uDF25"},
	{"signName":"AS", "cuneiform":"asz2", "val":"\uD808\uDC3E"},
	{"signName":"ZIZ", "cuneiform":"ziz2", "val":"\uD808\uDF69"},
	{"signName":"BANES", "cuneiform":"banesz", "val":"\uD809\uDC51"},
	{"signName":"BANLIMMU", "cuneiform":"banlimmu", "val":"\uD809\uDC52"},
	{"signName":"BANIA", "cuneiform":"bania", "val":"\uD809\uDC54"},
	{"signName":"MA", "cuneiform":"ma", "cuneiform1":"pesz3", "val":"\uD808\uDE20"},
	{"signName":"GAL", "cuneiform":"gal", "val":"\uD808\uDCF2"},
	{"signName":"GAL-KINDA", "cuneiform":"gal-kinda", "val":"\uD808\uDCF3"},
	{"signName":"BARA", "cuneiform":"bara2", "val":"\uD808\uDC48"},
	{"signName":"GUG", "cuneiform":"LU3", "cuneiform1":"SE3-GUNU", "cuneiform2":"gug2", "cuneiform3":"lu3", "cuneiform4":"sze3-gunu", "cuneiform5":"gar5", "val":"\uD808\uDE16"},
	{"signName":"GIN", "cuneiform":"gin2", "val":"\uD808\uDC86"},
	{"signName":"MIR", "cuneiform":"NIMGIR", "cuneiform1":"mir", "cuneiform2":"nimgir", "cuneiform3":"aga", "val":"\uD808\uDC87"},
	{"signName":"DUN4", "cuneiform":"UR-GUNU-SESSIG", "cuneiform1":"MIR-SESSIG", "cuneiform2":"dun4", "cuneiform3":"ur-gunu-szeszszig", "cuneiform4":"mir-szeszszig", "val":"\uD808\uDC88"},
	{"signName":"GIR", "cuneiform":"HA-GUNU", "cuneiform1":"gir", "cuneiform2":"ha-gunu", "cuneiform3":"bisz", "cuneiform4":"pesz", "val":"\uD808\uDD2B"},
	{"signName":"BUR", "cuneiform":"NIG-GUNU", "cuneiform1":"bur", "cuneiform2":"nig2-gunu", "val":"\uD808\uDC53"},
	{"signName":"A", "cuneiform":"a2", "cuneiform1":"ed", "cuneiform2":"et", "cuneiform3":"id", "cuneiform4":"it", "val":"\uD808\uDC09"},
	{"signName":"DA", "cuneiform":"da", "cuneiform1":"ta2", "val":"\uD808\uDC55"},
	{"signName":"GASAN", "cuneiform":"gaszan", "val":"\uD808\uDCFD"},
	{"signName":"U-GUNU", "cuneiform":"BUR3-GUNU", "cuneiform1":"u-gunu", "cuneiform2":"bur-gunu", "val":"\uD809\uDC34"},
	{"signName":"SIG7", "cuneiform":"IGI-GUNU", "cuneiform1":"sig7", "cuneiform2":"igi-gunu", "cuneiform3":"imma3", "cuneiform4":"se12", "cuneiform5":"ugur2", "val":"\uD808\uDD4A"},
	{"signName":"DUB", "cuneiform":"dub2", "val":"\uD808\uDC80"},
	{"signName":"BALAG", "cuneiform":"balag", "val":"\uD808\uDC46"},
	{"signName":"SA", "cuneiform":"sza", "cuneiform1":"en8", "val":"\uD808\uDEAD"},
	{"signName":"SU", "cuneiform":"szu", "val":"\uD808\uDED7"},
	{"signName":"KAD4", "cuneiform":"kad4", "cuneiform1":"kam3", "cuneiform2":"pesz5", "val":"\uD808\uDD92"},
	{"signName":"KAD5", "cuneiform":"kad5", "cuneiform1":"pesz6", "val":"\uD808\uDD93"},
	{"signName":"LUL", "cuneiform":"szatam", "cuneiform1":"lul", "cuneiform2":"nar", "cuneiform3":"ka5", "cuneiform4":"lib", "cuneiform5":"lu5", "cuneiform6":"lub", "cuneiform7":"pah", "val":"\uD808\uDE1C"},
	{"signName":"SA6", "cuneiform":"sa6", "val":"\uD808\uDEB7"},
	{"signName":"BISEBA3", "cuneiform":"GU4-GU4-LUGAL", "cuneiform1":"biszeba3", "cuneiform2":"gu4-gu4-lugal", "val":"\uD808\uDD21"},
	{"signName":"ALAM", "cuneiform":"GU4-GU4-NA", "cuneiform1":"alam", "cuneiform2":"gu4-gu4-na", "val":"\uD808\uDC29"},
	{"signName":"URI", "cuneiform":"BUR-BUR", "cuneiform1":"uri", "cuneiform2":"bur-bur", "val":"\uD808\uDF35"},
	{"signName":"GE23", "cuneiform":"DIS-TENU", "cuneiform1":"ge23", "cuneiform2":"disz-tenu", "val":"\uD808\uDC39"},
	{"signName":"GAM", "cuneiform":"gam", "cuneiform1":"gur2", "cuneiform2":"gurum", "val":"\uD808\uDCF5"},
	{"signName":"ILIMMU4", "cuneiform":"3-GE23", "cuneiform1":"ilimmu4", "cuneiform2":"3-ge23", "val":"\uD809\uDC48"},
	{"signName":"KUR", "cuneiform":"kur", "val":"\uD808\uDDB3"},
	{"signName":"KUR-KUR*", "cuneiform":"kur-kur*", "val":"\uD808\uDDB4"},
	{"signName":"SE", "cuneiform":"sze", "cuneiform1":"niga", "val":"\uD808\uDEBA"},
	{"signName":"BU", "cuneiform":"GID", "cuneiform1":"bu", "cuneiform2":"gid2", "cuneiform3":"bur12", "cuneiform4":"dur7", "cuneiform5":"kim3", "cuneiform6":"pu", "cuneiform7":"sud4", "val":"\uD808\uDC4D"},
	{"signName":"BU-BU", "cuneiform":"bu-bu", "val":"\uD808\uDC50"},
	{"signName":"SIRSIR", "cuneiform":"BU-BU-AB", "cuneiform1":"sirsir", "cuneiform2":"bu-bu-ab", "val":"\uD808\uDC4E"},
	{"signName":"SUD", "cuneiform":"BU-GUNU", "cuneiform1":"sud", "cuneiform2":"bu-gunu", "cuneiform3":"su3", "cuneiform4":"sug4", "val":"\uD808\uDEE4"},
	{"signName":"MUS", "cuneiform":"musz", "val":"\uD808\uDE32"},
	{"signName":"UTUKI", "cuneiform":"KUR-IR-GIDIM", "cuneiform1":"utuki", "cuneiform2":"kur2-ir-gidim2", "val":"\uD808\uDF59"},
	{"signName":"RI8", "cuneiform":"ri8", "val":"\uD808\uDE36"},
	{"signName":"MUS-MUS", "cuneiform":"musz-musz", "val":"\uD808\uDE38"},
	{"signName":"TIR", "cuneiform":"tir", "cuneiform1":"ezina3", "cuneiform2":"ter", "val":"\uD808\uDF01"},
	{"signName":"NINNI5", "cuneiform":"TIR-TIR", "cuneiform1":"ninni5", "cuneiform2":"tir-tir", "val":"\uD808\uDF03"},
	{"signName":"TIR-TIR-GAD-GAD-NIG-NIG", "cuneiform":"tir-tir-gad-gad-nig2-nig2", "val":"\uD808\uDF04"},
	{"signName":"SE-SE-GAD-GAD-NIG-NIG", "cuneiform":"sze-sze-gad-gad-nig2-nig2", "val":"\uD808\uDEBC"},
	{"signName":"SE-SE-TAB-TAB-NIG-NIG", "cuneiform":"sze-sze-tab-tab-nig2-nig2", "val":"\uD808\uDEBD"},
	{"signName":"U-U-SUR-SUR", "cuneiform":"u-u-sur-sur", "val":"\uD808\uDF0F"},
	{"signName":"U-U-PA-PA-NIG-NIG", "cuneiform":"u-u-pa-pa-nig2-nig2", "val":"\uD808\uDF0E"},
	{"signName":"TE", "cuneiform":"te", "cuneiform1":"gal5", "cuneiform2":"teg3", "cuneiform3":"temen", "cuneiform4":"ten", "val":"\uD808\uDEFC"},
	{"signName":"LIS", "cuneiform":"lisz", "val":"\uD808\uDDFA"},
	{"signName":":", "val":"\uD809\uDC71"},
	{"signName":"TAB*", "cuneiform":"tab*", "val":"\uD809\uDC4A"},
	{"signName":"KAM", "cuneiform":"HI-BAD", "cuneiform1":"kam", "cuneiform2":"hi-bad", "cuneiform3":"tu7", "cuneiform4":"utul2", "val":"\uD808\uDD9A"},
	{"signName":"ut", "cuneiform":"u4", "cuneiform1":"ud", "cuneiform2":"babbar", "cuneiform3":"bir2", "cuneiform4":"dag2", "cuneiform5":"had2", "cuneiform6":"szamasz", "cuneiform7":"tam", "val":"\uD808\uDF13"},
	{"signName":"ITIMA", "cuneiform":"UD-MI", "cuneiform1":"itima2", "cuneiform2":"ud-mi", "val":"\uD808\uDF16"},
	{"signName":"wa", "cuneiform":"pi", "cuneiform1":"be6", "cuneiform2":"be3", "cuneiform3":"tal2", "cuneiform4":"we", "cuneiform5":"pe", "cuneiform6":"pi", "cuneiform7":"wi", "val":"\uD808\uDE7F"},
	{"signName":"PI-PI", "cuneiform":"TALTAL", "cuneiform1":"pi-pi", "cuneiform2":"taltal", "val":"\uD808\uDE89"},
	{"signName":"PI-AB", "cuneiform":"pi-ab", "val":"\uD808\uDE81"},
	{"signName":"PI-I", "cuneiform":"pi-i", "val":"\uD808\uDE85"},
	{"signName":"PI-BI", "cuneiform":"pi-bi", "val":"\uD808\uDE82"},
	{"signName":"PI-U", "cuneiform":"pi-u2", "val":"\uD808\uDE89"},
	{"signName":"PI-E", "cuneiform":"pi-e", "val":"\uD808\uDE84"},
	{"signName":"PI-BU", "cuneiform":"pi-bu", "val":"\uD808\uDE83"},
	{"signName":"PI-U", "cuneiform":"pi-u", "val":"\uD808\uDE87"},
	{"signName":"PI-IB", "cuneiform":"pi-ib", "val":"\uD808\uDE86"},
	{"signName":"PI-A", "cuneiform":"pi-a", "val":"\uD808\uDE80"},
	{"signName":"SA3", "cuneiform":"SAG4", "cuneiform1":"sza3", "cuneiform2":"szag4", "val":"\uD808\uDEAE"},
	{"signName":"SA3-BAD", "cuneiform":"sza3-bad", "val":"\uD808\uDEB0"},
	{"signName":"SA3-TUR", "cuneiform":"sza3-tur", "val":"\uD808\uDEB4"},
	{"signName":"SA3-NE", "cuneiform":"sza3-ne", "val":"\uD808\uDEB2"},
	{"signName":"SA3-GIS", "cuneiform":"sza3-gisz", "val":"\uD808\uDEB1"},
	{"signName":"SA3-U", "cuneiform":"sza3-u", "val":"\uD808\uDEB5"},
	{"signName":"PES4", "cuneiform":"SA3-A", "cuneiform1":"sza3-a", "cuneiform2":"pesz4", "cuneiform3":"bir7", "cuneiform4":"iszkila", "val":"\uD808\uDEAF"},
	{"signName":"SA3-SU", "cuneiform":"sza3-szu2", "val":"\uD808\uDEB3"},
	{"signName":"UH", "cuneiform":"UD-KUSU", "cuneiform1":"uh2", "cuneiform2":"ud-kuszu2", "val":"\uD808\uDF14"},
	{"signName":"ERIM", "cuneiform":"ZALAG", "cuneiform1":"erim", "cuneiform2":"zalag2", "cuneiform3":"erin2", "cuneiform4":"rin2", "val":"\uD808\uDC9F"},
	{"signName":"PIR", "cuneiform":"pir2", "val":"\uD808\uDC9F"},
	{"signName":"NUNUZ", "cuneiform":"nunuz", "cuneiform1":"nida", "cuneiform2":"nus", "val":"\uD808\uDE6D"},
	{"signName":"LAHTAN", "cuneiform":"NUNUZ-AB-LA", "cuneiform1":"lahtan", "cuneiform2":"nunuz-ab2-la", "val":"\uD808\uDE74"},
	{"signName":"NUNUZ-AB-SILA3", "cuneiform":"LAHTAN", "cuneiform1":"nunuz-ab2-sila3", "cuneiform2":"lahtan2", "val":"\uD808\uDE76"},
	{"signName":"NUNUZ-AB-KAD3", "cuneiform":"nunuz-ab2-kad3", "val":"\uD808\uDE73"},
	{"signName":"USAN3", "cuneiform":"NUNUZ-AB-ASGAB", "cuneiform1":"usan3", "cuneiform2":"nunuz-ab2-aszgab", "val":"\uD808\uDE6E"},
	{"signName":"NUNUZ-AB-NE", "cuneiform":"nunuz-ab2-ne", "val":"\uD808\uDE75"},
	{"signName":"MUD3", "cuneiform":"NUNUZ-AB-BI", "cuneiform1":"mud3", "cuneiform2":"nunuz-ab2-bi", "val":"\uD808\uDE6F"},
	{"signName":"NUNUZ-AB-GU4", "cuneiform":"nunuz-ab2-gu4", "val":"\uD808\uDE71"},
	{"signName":"NUNUZ-AB-U-BA", "cuneiform":"nunuz-ab2-u2-ba", "val":"\uD808\uDE77"},
	{"signName":"NUNUZ-AB-DUG", "cuneiform":"nunuz-ab2-dug", "val":"\uD808\uDE70"},
	{"signName":"NUNUZ-AB-SIG7", "cuneiform":"nunuz-ab2-sig7", "val":"\uD808\uDE72"},
	{"signName":"ZIB", "cuneiform":"zib", "val":"\uD808\uDF66"},
	{"signName":"ZIB*", "cuneiform":"zib*", "val":"\uD808\uDF67"},
	{"signName":"ES23", "cuneiform":"esz23", "val":"\uD809\uDC4B"},
	{"signName":"HI", "cuneiform":"DUG3", "cuneiform1":"hi", "cuneiform2":"dug3", "cuneiform3":"da10", "cuneiform4":"du10", "cuneiform5":"dub3", "cuneiform6":"he", "cuneiform7":"szar2", "val":"\uD808\uDD2D"},
	{"signName":"SAR", "cuneiform":"szar", "val":"\uD808\uDEB9"},
	{"signName":"SUR3", "cuneiform":"HI-AS", "cuneiform1":"sur3", "cuneiform2":"hi-asz", "val":"\uD808\uDD2E"},
	{"signName":"ALEPH", "cuneiform":"aleph", "val":"\uD808\uDC2A"},
	{"signName":"AH", "cuneiform":"HI-NUN", "cuneiform1":"ah", "cuneiform2":"hi-nun", "cuneiform3":"a'", "cuneiform4":"eh", "cuneiform5":"ih", "cuneiform6":"uh", "cuneiform7":"umun3", "val":"\uD808\uDD34"},
	{"signName":"IM", "cuneiform":"im", "cuneiform1":"did", "cuneiform2":"em", "cuneiform3":"enegir", "cuneiform4":"iszkur", "cuneiform5":"karkara", "cuneiform6":"ni2", "cuneiform7":"tum9", "val":"\uD808\uDD4E"},
	{"signName":"NI2", "cuneiform":"ni2", "val":"\uD808\uDE4E"},
	{"signName":"IM-IM", "cuneiform":"im-im", "val":"\uD808\uDD50"},
	{"signName":"4-IM", "cuneiform":"4-im", "val":"\uD808\uDD52"},
	{"signName":"IM-KID", "cuneiform":"im-kid2", "val":"\uD808\uDD4F"},
	{"signName":"BIR", "cuneiform":"HI-SE", "cuneiform1":"bir", "cuneiform2":"hi-sze", "cuneiform3":"dubur", "cuneiform4":"girisz", "val":"\uD808\uDD35"},
	{"signName":"ur5", "cuneiform":"mur", "cuneiform1":"har", "cuneiform2":"hi-asz", "cuneiform3":"ar3", "cuneiform4":"hur", "cuneiform5":"kin2", "cuneiform6":"kinkin", "cuneiform7":"mar6", "val":"\uD808\uDD2F"},
	{"signName":"SUHUR", "cuneiform":"suhur", "val":"\uD808\uDEE6"},
	{"signName":"GE22", "cuneiform":"ge22", "val":"\uD808\uDC3A"},
	{"signName":"SUSUR", "cuneiform":"szuszur2", "val":"\uD808\uDC3D"},
	{"signName":"SAR-GAD", "cuneiform":"szar2-gad", "val":"\uD808\uDD32"},
	{"signName":"SAR-GAL-MIN", "cuneiform":"szar2-gal-min", "val":"\uD809\uDC33"},
	{"signName":"SAR-U", "cuneiform":"szar2-u", "val":"\uD809\uDC2C"},
	{"signName":"SAR-MAN", "cuneiform":"szar2-man", "val":"\uD809\uDC2D"},
	{"signName":"SAR-ES", "cuneiform":"szar2-esz", "val":"\uD808\uDC2D"},
	{"signName":"SAR-NIMIN", "cuneiform":"szar2-nimin", "val":"\uD809\uDC2E"},
	{"signName":"SAR-NINNU", "cuneiform":"szar2-ninnu", "val":"\uD809\uDC31"},
	{"signName":"SAR-DIS", "cuneiform":"HI-DIS", "cuneiform1":"szar2-disz", "cuneiform2":"hi-disz", "val":"\uD808\uDD31"},
	{"signName":"HI-KIN", "cuneiform":"hi-kin", "val":"\uD808\uDD33"},
	{"signName":"U", "cuneiform":"u", "cuneiform1":"10", "cuneiform2":"bur3", "cuneiform3":"buru3", "cuneiform4":"szu4","val":"\uD808\uDF0B"},
	{"signName":"AB", "cuneiform":"ab2", "val":"\uD808\uDC16"},
	{"signName":"AB-KID", "cuneiform":"ab2-kid2", "val":"\uD808\uDC1B"},
	{"signName":"AB-KAR", "cuneiform":"ab2-kar2", "val":"\uD808\uDC18"},
	{"signName":"GIRI16", "cuneiform":"GIR3-KAR", "cuneiform1":"giri16", "cuneiform2":"gir3-kar2", "cuneiform3":"gir16", "cuneiform4":"girid2", "val":"\uD808\uDD0C"},
	{"signName":"LILIZ", "cuneiform":"AB-BALAG", "cuneiform1":"liliz", "cuneiform2":"ab2-balag", "val":"\uD808\uDC17"},
	{"signName":"LIBIS", "cuneiform":"AB-SA3", "cuneiform1":"libisz", "cuneiform2":"ab2-sza3", "val":"\uD808\uDC1A"},
	{"signName":"KIS", "cuneiform":"kisz", "val":"\uD808\uDDA7"},
	{"signName":"MEZE", "cuneiform":"AB-ME-EN", "cuneiform1":"meze", "cuneiform2":"ab2-me-en", "val":"\uD808\uDC19"},
	{"signName":"MI", "cuneiform":"mi", "cuneiform1":"gig2", "cuneiform2":"gi6", "cuneiform3":"ku10", "cuneiform4":"me2", "val":"\uD808\uDE2A"},
	{"signName":"GUL", "cuneiform":"SUN", "cuneiform1":"gul", "cuneiform2":"sun2", "cuneiform3":"isimu2", "cuneiform4":"kul2", "cuneiform5":"si23", "cuneiform6":"sumun2", "val":"\uD808\uDD22"},
	{"signName":"PAN", "cuneiform":"pan", "val":"\uD808\uDE7C"},
	{"signName":"GIM", "cuneiform":"DIM", "cuneiform1":"gim", "cuneiform2":"dim2", "val":"\uD808\uDC76"},
	{"signName":"KISIM5", "cuneiform":"kisim5", "val":"\uD808\uDDA8"},
	{"signName":"GINGIRA", "cuneiform":"KISIM5-KISIM5", "cuneiform1":"gingira", "cuneiform2":"kisim5-kisim5", "val":"\uD808\uDDA9"},
	{"signName":"DUBUR", "cuneiform":"HI-U", "cuneiform1":"dubur2", "cuneiform2":"hi-u", "val":"\uD808\uDD36"},
	{"signName":"NA", "cuneiform":"na2", "val":"\uD808\uDE3F"},
	{"signName":"NIM", "cuneiform":"nim", "cuneiform1":"dehi3", "cuneiform2":"elam", "cuneiform3":"tum4", "val":"\uD808\uDE4F"},
	{"signName":"TUM3", "cuneiform":"NIM-KAR", "cuneiform1":"tum3", "cuneiform2":"nim-kar2", "val":"\uD808\uDE50"},
	{"signName":"KIR7", "cuneiform":"NIM-NIG-KAR", "cuneiform1":"kir7", "cuneiform2":"nim-nig2-kar2", "val":"\uD808\uDE51"},
	{"signName":"LAM", "cuneiform":"lam", "val":"\uD808\uDDF4"},
	{"signName":"LAM-KUR", "cuneiform":"lam-kur", "val":"\uD808\uDDF5"},
	{"signName":"AMAR", "cuneiform":"ZUR", "cuneiform1":"amar", "cuneiform2":"zur", "cuneiform3":"mar2", "val":"\uD808\uDC2B"},
	{"signName":"SISKUR", "cuneiform":"AMAR-SE", "cuneiform1":"siskur", "cuneiform2":"amar-sze", "val":"\uD808\uDC2C"},
	{"signName":"UL", "cuneiform":"DU7", "cuneiform1":"ul", "cuneiform2":"du7", "val":"\uD808\uDF0C"},
	{"signName":"GIR3", "cuneiform":"gir3", "cuneiform1":"er9", "cuneiform2":"giri3", "cuneiform3":"szakkan2", "val":"\uD808\uDD0A"},
	{"signName":"PIRIG", "cuneiform":"pirig", "val":"\uD808\uDE8A"},
	{"signName":"GIR3-GIR3*", "cuneiform":"gir3-gir3*", "val":"\uD808\uDE8E"},
	{"signName":"LULIM", "cuneiform":"GIR3-LU-IGI", "cuneiform1":"lulim", "cuneiform2":"gir3-lu-igi", "val":"\uD808\uDD0E"},
	{"signName":"ALIM", "cuneiform":"GIR3-A-IGI", "cuneiform1":"alim", "cuneiform2":"gir3-a-igi", "val":"\uD808\uDD0B"},
	{"signName":"GIR3-IGI", "cuneiform":"gir3-igi", "val":"\uD808\uDD0D"},
	{"signName":"DUGUD", "cuneiform":"dugud", "val":"\uD808\uDC82"},
	{"signName":"ES", "cuneiform":"3-U", "cuneiform1":"esz", "cuneiform2":"3-u", "cuneiform3":"30", "val":"\uD808\uDF0D"},
	{"signName":"NIMIN", "cuneiform":"4-U", "cuneiform1":"nimin", "cuneiform2":"4-u", "cuneiform3":"40", "val":"\uD809\uDC0F"},
	{"signName":"MASGI", "cuneiform":"BARGI", "cuneiform1":"maszgi", "cuneiform2":"bargi", "val":"\uD808\uDF10"},
	{"signName":"NINNU", "cuneiform":"5-U", "cuneiform1":"ninnu", "cuneiform2":"5-u", "cuneiform3":"50", "val":"\uD809\uDC10"},
	{"signName":"LX", "cuneiform":"6-U", "cuneiform1":"lx", "cuneiform2":"6-u", "cuneiform3":"60", "val":"\uD809\uDC11"},
	{"signName":"7-U", "cuneiform":"7-u", "cuneiform1":"70", "val":"\uD809\uDC12"},
	{"signName":"8-U", "cuneiform":"8-u", "cuneiform1":"80", "val":"\uD809\uDC13"},
	{"signName":"9-U", "cuneiform":"9-u", "cuneiform1":"90", "val":"\uD809\uDC14"},
	{"signName":"LAGAR", "cuneiform":"lagar", "val":"\uD808\uDDEC"},
	{"signName":"DU6", "cuneiform":"LAGAR-GUNU", "cuneiform1":"du6", "cuneiform2":"lagar-gunu", "val":"\uD808\uDDEF"},
	{"signName":"DU6-DU6-SE", "cuneiform":"du6-du6-sze", "val":"\uD808\uDDF0"},
	{"signName":"SU7", "cuneiform":"LAGAR-SE", "cuneiform1":"su7", "cuneiform2":"lagar-sze", "cuneiform3":"sur12", "val":"\uD808\uDDED"},
	{"signName":"LAGAR-SE-SUM", "cuneiform":"lagar-sze-sum", "val":"\uD808\uDDEE"},
	{"signName":"IGI", "cuneiform":"SI", "cuneiform1":"LIM", "cuneiform2":"igi", "cuneiform3":"szi", "cuneiform4":"lim", "cuneiform5":"ge8", "cuneiform6":"gi8", "cuneiform7":"lib4", "val":"\uD808\uDD46"},
	{"signName":"DIMSAR", "cuneiform":"dimsar", "val":"\uD808\uDD49"},
	{"signName":"AR", "cuneiform":"IGI-RI", "cuneiform1":"ar", "cuneiform2":"igi-ri", "val":"\uD808\uDD48"},
	{"signName":"U3", "cuneiform":"IGI-DIB", "cuneiform1":"u3", "cuneiform2":"igi-dib", "val":"\uD808\uDD47"},
	{"signName":"DI", "cuneiform":"di", "cuneiform1":"de", "cuneiform2":"sa2", "cuneiform3":"silim", "val":"\uD808\uDC72"},
	{"signName":"KI", "cuneiform":"ki", "cuneiform1":"ge5", "cuneiform2":"gi5", "cuneiform3":"ke", "cuneiform4":"qi2", "val":"\uD808\uDDA0"},
	{"signName":"KI-BAD", "cuneiform":"ki-bad", "val":"\uD808\uDDA1"},
	{"signName":"KI-UD", "cuneiform":"ki-ud", "val":"\uD808\uDDA3"},
	{"signName":"KI-U", "cuneiform":"ki-u", "val":"\uD808\uDDA2"},
	{"signName":"PES", "cuneiform":"pesz2", "val":"\uD808\uDE7E"},
	{"signName":"KISI4", "cuneiform":"kiszi4", "val":"\uD808\uDE94"},
	{"signName":"SUL", "cuneiform":"DUN", "cuneiform1":"szul", "cuneiform2":"dun", "cuneiform3":"dur9", "cuneiform4":"sul", "cuneiform5":"szah2", "cuneiform6":"zu7", "val":"\uD808\uDC84"},
	{"signName":"KUG", "cuneiform":"KU3", "cuneiform1":"kug", "cuneiform2":"ku3", "val":"\uD808\uDDAC"},
	{"signName":"PAD", "cuneiform":"SUK", "cuneiform1":"pad", "cuneiform2":"szuk", "val":"\uD808\uDE7B"},
	{"signName":"DIS", "cuneiform":"disz", "cuneiform1":"1", "cuneiform2":"60", "cuneiform3":"esz4", "val":"\uD808\uDC79"},
	{"signName":"LAL", "cuneiform":"LA", "cuneiform1":"lal", "cuneiform2":"la2", "cuneiform3":"suru5", "val":"\uD808\uDDF2"},
	{"signName":"LAL", "cuneiform":"LAL-LAL", "cuneiform1":"lal2", "cuneiform2":"lal-lal", "val":"\uD808\uDDF3"},
	{"signName":"ME", "cuneiform":"me", "cuneiform1":"100", "cuneiform2":"ba13", "cuneiform3":"iszib", "cuneiform4":"men2", "val":"\uD808\uDE28"},
	{"signName":"ni10", "cuneiform":"lagab", "cuneiform1":"ellag", "cuneiform2":"girin", "cuneiform3":"gur4", "cuneiform4":"hab", "cuneiform5":"rin", "cuneiform6":"nigin2", "cuneiform7":"kilib", "val":"\uD808\uDDB8"},
	{"signName":"ENGUR", "cuneiform":"LAGAB-HAL", "cuneiform1":"engur", "cuneiform2":"lagab-hal", "val":"\uD808\uDDC9"},
	{"signName":"LAGAB-AN", "cuneiform":"lagab-an", "val":"\uD808\uDDBE"},
	{"signName":"LAGAB-KID", "cuneiform":"lagab-kid2", "val":"\uD808\uDDE3"},
	{"signName":"GIGIR", "cuneiform":"LAGAB-BAD", "cuneiform1":"lagab-bad", "cuneiform2":"gigir", "val":"\uD808\uDDC0"},
	{"signName":"ESIR", "cuneiform":"LAGAB-NUMUN", "cuneiform1":"esir2", "cuneiform2":"lagab-numun", "val":"\uD808\uDDD2"},
	{"signName":"LAGAB-NUMUN-HI-A", "cuneiform":"lagab-numun-hi-a", "val":"\uD808\uDDD3"},
	{"signName":"LAGAB-EN", "cuneiform":"lagab-en", "val":"\uD808\uDDC3"},
	{"signName":"LAGAB-DAR", "cuneiform":"lagab-dar", "val":"\uD808\uDDC2"},
	{"signName":"LAGAB-GU4-GU4", "cuneiform":"U8", "cuneiform1":"lagab-gu4-gu4", "cuneiform2":"u8", "val":"\uD808\uDDC7"},
	{"signName":"ZAR", "cuneiform":"LAGAB-SUM", "cuneiform1":"zar", "cuneiform2":"lagab-sum", "val":"\uD808\uDDE1"},
	{"signName":"UDUB", "cuneiform":"LAGAB-NE", "cuneiform1":"udub", "cuneiform2":"lagab-ne", "val":"\uD808\uDDDB"},
	{"signName":"LAGAB-BI", "cuneiform":"lagab-bi", "val":"\uD808\uDDC1"},
	{"signName":"LAGAB-US", "cuneiform":"lagab-usz", "val":"\uD808\uDDEA"},
	{"signName":"LAGAB-SITA", "cuneiform":"lagab-szita2", "val":"\uD808\uDDDE"},
	{"signName":"LAGAB-SITA-ERIM", "cuneiform":"lagab-szita2-erim", "val":"\uD808\uDDDD"},
	{"signName":"LAGAB-GU4", "cuneiform":"lagab-gu4", "val":"\uD808\uDDC6"},
	{"signName":"LAGAB-AL", "cuneiform":"lagab-al", "val":"\uD808\uDDBD"},
	{"signName":"LAGAB-U-AS", "cuneiform":"lagab-u2-asz", "val":"\uD808\uDDE8"},
	{"signName":"LAGAB-GA", "cuneiform":"lagab-ga", "val":"\uD808\uDDC4"},
	{"signName":"SARA", "cuneiform":"LAGAB-SIG7", "cuneiform1":"szara2", "cuneiform2":"lagab-sig7", "val":"\uD808\uDDCB"},
	{"signName":"LAGAB-LUL", "cuneiform":"lagab-lul", "val":"\uD808\uDDD7"},
	{"signName":"LAGAB-GE23", "cuneiform":"lagab-ge23", "val":"\uD808\uDDBF"},
	{"signName":"LAGAB-SE-SUM", "cuneiform":"lagab-sze-sum", "val":"\uD808\uDDDC"},
	{"signName":"LAGAB-MUS", "cuneiform":"lagab-musz", "val":"\uD808\uDDDA"},
	{"signName":"LAGAB-KAR-SU-NA", "cuneiform":"lagab-kar-su-na", "val":"\uD808\uDDE4"},
	{"signName":"LAGAB-LIS", "cuneiform":"lagab-lisz", "val":"\uD808\uDDD5"},
	{"signName":"LAGAB-UD", "cuneiform":"lagab-ud", "val":"\uD808\uDDE9"},
	{"signName":"LAGAB-AH", "cuneiform":"lagab-ah", "val":"\uD808\uDDCA"},
	{"signName":"LAGAB-IM", "cuneiform":"lagab-im", "val":"\uD808\uDDCC"},
	{"signName":"LAGAB-U", "cuneiform":"ub4", "cuneiform1":"lagab-u", "cuneiform2":"tul2", "cuneiform3":"bu4", "cuneiform4":"dul2", "cuneiform5":"gigir2", "cuneiform6":"hab2", "cuneiform7":"pu2", "val":"\uD808\uDDE5"},
	{"signName":"LAGAB-U-A", "cuneiform":"lagab-u-a", "cuneiform1":"umah", "val":"\uD808\uDDE6"},
	{"signName":"LAGAB-ES", "cuneiform":"BUL", "cuneiform1":"lagab-esz", "cuneiform2":"bul", "val":"\uD808\uDDE7"},
	{"signName":"LAGAB-KI", "cuneiform":"lagab-ki", "val":"\uD808\uDDCF"},
	{"signName":"GARIM", "cuneiform":"LAGAB-KUG", "cuneiform1":"garim", "cuneiform2":"lagab-kug", "val":"\uD808\uDDD1"},
	{"signName":"LAGAB-ME", "cuneiform":"lagab-me", "val":"\uD808\uDDD8"},
	{"signName":"LAGAB-ME-EN", "cuneiform":"lagab-me-en", "val":"\uD808\uDDD9"},
	{"signName":"LAGAB-LU", "cuneiform":"lagab-lu", "val":"\uD808\uDDD6"},
	{"signName":"LAGAB-KIN", "cuneiform":"lagab-kin", "val":"\uD808\uDDD0"},
	{"signName":"SUG", "cuneiform":"LAGAB-A", "cuneiform1":"sug", "cuneiform2":"lagab-a", "cuneiform3":"ambar", "cuneiform4":"as4", "cuneiform5":"bunig", "val":"\uD808\uDDB9"},
	{"signName":"LAGAB-A-DA-HA", "cuneiform":"lagab-a-da-ha", "val":"\uD808\uDDBA"},
	{"signName":"LAGAB-A-LAL", "cuneiform":"lagab-a-lal", "val":"\uD808\uDDBC"},
	{"signName":"LAGAB-A-NIG", "cuneiform":"LAGAB-A-GAR", "cuneiform1":"lagab-a-nig2", "cuneiform2":"lagab-a-gar", "val":"\uD808\uDDBB"},
	{"signName":"LAGAB-HA", "cuneiform":"lagab-ha", "val":"\uD808\uDDC8"},
	{"signName":"LAGAB-NIG", "cuneiform":"lagab-nig2", "val":"\uD808\uDDC5"},
	{"signName":"LAGAB-SU", "cuneiform":"lagab-szu2", "val":"\uD808\uDDDF"},
	{"signName":"LAGAB-SU-SU", "cuneiform":"lagab-szu2-szu2", "val":"\uD808\uDDE0"},
	{"signName":"NIGIN", "cuneiform":"LAGAB-LAGAB", "cuneiform1":"lagab-lagab", "cuneiform2":"nigin", "val":"\uD808\uDDD4"},
	{"signName":"4-LAGAB", "cuneiform":"4-lagab", "val":"\uD808\uDDEB"},
	{"signName":"IB", "cuneiform":"ib", "cuneiform1":"dara2", "cuneiform2":"eb", "cuneiform3":"ip", "cuneiform4":"urasz", "cuneiform5":"urta", "val":"\uD808\uDD41"},
	{"signName":"dab5", "cuneiform":"ugu4", "cuneiform1":"gu5", "cuneiform2":"ku", "cuneiform3":"tukul", "cuneiform4":"tusz", "cuneiform5":"bid3", "cuneiform6":"bu7", "cuneiform7":"dib2", "val":"\uD808\uDDAA"},
	{"signName":"DUR", "cuneiform":"dur2", "val":"\uD808\uDC89"},
	{"signName":"TUG", "cuneiform":"tug2", "cuneiform1":"azlag2", "cuneiform2":"dul5", "cuneiform3":"mu4", "cuneiform4":"mur10", "cuneiform5":"nam2", "cuneiform6":"tuku2", "cuneiform7":"umusz", "val":"\uD808\uDF06"},
	{"signName":"NAM", "cuneiform":"nam2", "val":"\uD808\uDE47"},
	{"signName":"ub2", "cuneiform":"sumun", "cuneiform1":"hug", "cuneiform2":"sze3", "cuneiform3":"gi7", "cuneiform4":"esz2", "cuneiform5":"egir2", "cuneiform6":"esze2", "cuneiform7":"gir15", "val":"\uD808\uDCA0"},
	{"signName":"ZI3", "cuneiform":"zi3", "cuneiform1":"zid2", "val":"\uD808\uDF65"},
	{"signName":"LU", "cuneiform":"UDU", "cuneiform1":"lu", "cuneiform2":"udu", "cuneiform3":"lug", "cuneiform4":"nu12", "val":"\uD808\uDDFB"},
	{"signName":"DIB", "cuneiform":"DAB", "cuneiform1":"dib", "cuneiform2":"dab", "val":"\uD808\uDC73"},
	{"signName":"AD3", "cuneiform":"LU-BAD", "cuneiform1":"ad3", "cuneiform2":"lu-bad", "val":"\uD808\uDDFC"},
	{"signName":"KIN", "cuneiform":"kin", "cuneiform1":"gur10", "cuneiform2":"kig2", "cuneiform3":"saga11", "val":"\uD808\uDDA5"},
	{"signName":"SIG", "cuneiform":"SIK", "cuneiform1":"sig2", "cuneiform2":"sik2", "val":"\uD808\uDEE0"},
	{"signName":"DARA4", "cuneiform":"SIG-AS", "cuneiform1":"dara4", "cuneiform2":"sig2-asz", "val":"\uD808\uDC71"},
	{"signName":"EREN", "cuneiform":"SIG-NUN", "cuneiform1":"eren", "cuneiform2":"sig2-nun", "cuneiform3":"sze22", "cuneiform4":"szesz4", "val":"\uD808\uDC9E"},
	{"signName":"GUR7", "cuneiform":"SIG-AH-ME-U", "cuneiform1":"gur7", "cuneiform2":"sig2-ah-me-u", "val":"\uD808\uDD26"},
	{"signName":"MUNSUB", "cuneiform":"MUNSUB", "cuneiform1":"SIG-SUHUR", "cuneiform2":"munszub", "cuneiform3":"munsub", "cuneiform4":"sig2-suhur", "val":"\uD808\uDE30"},
	{"signName":"SES", "cuneiform":"SIG-LAM", "cuneiform1":"szesz2", "cuneiform2":"sig2-lam", "val":"\uD808\uDEC1"},
	{"signName":"MIN", "cuneiform":"min", "cuneiform1":"2", "val":"\uD808\uDE2B"},
	{"signName":"SUSANA", "cuneiform":"szuszana", "val":"\uD809\uDC5A"},
	{"signName":"TUK", "cuneiform":"TUG", "cuneiform1":"tuk", "cuneiform2":"tug", "cuneiform3":"tuku", "cuneiform4":"du12", "val":"\uD808\uDF07"},
	{"signName":"UR", "cuneiform":"ur", "cuneiform1":"tesz2", "val":"\uD808\uDF28"},
	{"signName":"URBINGU", "cuneiform":"UR-UR", "cuneiform1":"urbingu", "cuneiform2":"ur-ur", "val":"\uD808\uDF29"},
	{"signName":"UR-SESSIG", "cuneiform":"ur-szeszszig", "val":"\uD808\uDF2A"},
	{"signName":"GIDIM", "cuneiform":"gidim", "val":"\uD808\uDD07"},
	{"signName":"SANABI", "cuneiform":"szanabi", "val":"\uD809\uDC5B"},
	{"signName":"UDUG", "cuneiform":"udug", "val":"\uD808\uDF1C"},
	{"signName":"ES5", "cuneiform":"esz5", "cuneiform1":"3", "val":"\uD809\uDC08"},
	{"signName":"UR4", "cuneiform":"ur4", "val":"\uD808\uDF34"},
	{"signName":"GIN", "cuneiform":"TUN3", "cuneiform1":"gin2", "cuneiform2":"tun3", "cuneiform3":"du5", "val":"\uD808\uDC85"},
	{"signName":"KINGUSILA", "cuneiform":"kingusila", "val":"\uD809\uDC5C"},
	{"signName":"A", "cuneiform":"a", "cuneiform1":"dur5", "cuneiform2":"duru5", "val":"\uD808\uDC00"},
	{"signName":"A-TU-GAB-LIS", "cuneiform":"a-tu-gab-lisz", "val":"\uD808\uDC37"},
	{"signName":"AGAM", "cuneiform":"A-BAD", "cuneiform1":"agam", "cuneiform2":"a-bad", "val":"\uD808\uDC02"},
	{"signName":"A-SAG", "cuneiform":"a-sag", "val":"\uD808\uDC08"},
	{"signName":"A-MUS", "cuneiform":"a-musz", "val":"\uD808\uDC07"},
	{"signName":"A-DU6", "cuneiform":"a-du6", "val":"\uD808\uDC06"},
	{"signName":"A-IGI", "cuneiform":"a-igi", "cuneiform1":"er2", "val":"\uD808\uDC05"},
	{"signName":"A-A", "cuneiform":"EDURU", "cuneiform1":"a-a", "cuneiform2":"eduru", "val":"\uD808\uDC01"},
	{"signName":"A-HA", "cuneiform":"ZAH3", "cuneiform1":"a-ha", "cuneiform2":"zah3", "val":"\uD808\uDC04"},
	{"signName":"NIGIDAMIN", "cuneiform":"DIS-DIS", "cuneiform1":"nigidamin", "cuneiform2":"disz-disz", "val":"\uD809\uDC56"},
	{"signName":"NIGIDAES", "cuneiform":"DIS-DIS-DIS", "cuneiform1":"nigidaesz", "cuneiform2":"disz-disz-disz", "val":"\uD809\uDC57"},
	{"signName":"ZA", "cuneiform":"LIMMU5", "cuneiform1":"NIGIDALIMMU", "cuneiform2":"za", "cuneiform3":"limmu5", "cuneiform4":"nigidalimmu", "cuneiform5":"4", "cuneiform6":"sa3", "val":"\uD808\uDF5D"},
	{"signName":"HA", "cuneiform":"KU6", "cuneiform1":"ha", "cuneiform2":"ku6", "cuneiform3":"pesz11", "val":"\uD808\uDD29"},
	{"signName":"ZUBUD", "cuneiform":"HA-TENU", "cuneiform1":"zubud", "cuneiform2":"ha-tenu", "val":"\uD808\uDD2A"},
	{"signName":"NIG", "cuneiform":"GAR", "cuneiform1":"nig2", "cuneiform2":"gar", "cuneiform3":"NINDA", "cuneiform4":"ninda", "cuneiform5":"ni3", "cuneiform6":"sza2", "cuneiform7":"nindan", "val":"\uD808\uDCFB"},
	{"signName":"LIMMU", "cuneiform":"limmu", "val":"\uD809\uDC3C"},
	{"signName":"IA", "cuneiform":"ia2", "cuneiform1":"5", "val":"\uD809\uDC0A"},
	{"signName":"AS3", "cuneiform":"asz3", "cuneiform1":"6", "val":"\uD809\uDC0B"},
	{"signName":"IMIN", "cuneiform":"imin", "cuneiform1":"7", "val":"\uD808\uDD53"},
	{"signName":"USSU", "cuneiform":"ussu", "cuneiform1":"8", "val":"\uD809\uDC0D"},
	{"signName":"DIS-DIS-DIS", "cuneiform":"disz-disz-disz", "val":"\uD809\uDC49"},
	{"signName":"ILIMMU", "cuneiform":"ilimmu", "cuneiform1":"9", "val":"\uD809\uDC46"},
	{"signName":"SU", "cuneiform":"szu2", "cuneiform1":"szusz2", "val":"\uD808\uDED9"},
	{"signName":"HUL", "cuneiform":"hul2", "cuneiform1":"bibra", "cuneiform2":"gukkal", "cuneiform3":"kusz8", "cuneiform4":"ukusz2", "val":"\uD808\uDD3E"},
	{"signName":"SEG9", "cuneiform":"szeg9", "cuneiform1":"kiszi6", "val":"\uD808\uDEBE"},
	{"signName":"SIG", "cuneiform":"sig", "cuneiform1":"si11", "cuneiform2":"sik", "val":"\uD808\uDEDD"},
	{"signName":"MUNUS", "cuneiform":"SAL", "cuneiform1":"munus", "cuneiform2":"sal", "cuneiform3":"gal4", "cuneiform4":"mi2", "val":"\uD808\uDEA9"},
	{"signName":"ZUM", "cuneiform":"zum", "cuneiform1":"hasz4", "cuneiform2":"rig2", "cuneiform3":"sum2", "val":"\uD808\uDF6E"},
	{"signName":"ZUM", "cuneiform":"ZUM-LAGAM", "cuneiform1":"zum2", "cuneiform2":"zum-lagam", "val":"\uD808\uDEAA"},
	{"signName":"DAM", "cuneiform":"dam", "val":"\uD808\uDC6E"},
	{"signName":"GU", "cuneiform":"gu", "val":"\uD808\uDD16"},
	{"signName":"SUH3", "cuneiform":"suh3", "val":"\uD808\uDD17"},
	{"signName":"NAGAR", "cuneiform":"nagar", "val":"\uD808\uDE44"},
	{"signName":"KUSU", "cuneiform":"kuszu2", "val":"\uD808\uDDB5"},
	{"signName":"EL", "cuneiform":"el", "cuneiform1":"il5", "cuneiform2":"sikil", "val":"\uD808\uDC96"},
	{"signName":"LUM", "cuneiform":"lum", "cuneiform1":"gum2", "cuneiform2":"gun5", "cuneiform3":"guz", "cuneiform4":"hum", "cuneiform5":"huz", "cuneiform6":"num2", "val":"\uD808\uDE1D"},
	{"signName":"MURGU", "cuneiform":"murgu2", "val":"\uD808\uDE31"},
	{"signName":"LUM-LUM", "cuneiform":"lum-lum", "val":"\uD808\uDE1E"},
	{"signName":"LUGUD3", "cuneiform":"lugud3", "val":"\uD808\uDE1F"},
	{"signName":"SIG4", "cuneiform":"MURGU", "cuneiform1":"sig4", "cuneiform2":"murgu", "cuneiform3":"gar8", "cuneiform4":"kulla", "cuneiform5":"szeg12", "val":"\uD808\uDEDE"},
	{"signName":"SIG4-SIG4-SU", "cuneiform":"sig4-sig4-szu2", "val":"\uD808\uDEDF"},
	{"signName":"AS-SUR", "cuneiform":"asz-sur", "cuneiform1":"asz-szur", "val":"\uD808\uDC38\uD808\uDEE9"},
	{"signName":"pusz2", "cuneiform":"pab-hal", "cuneiform1":"pap-hal", "val":"\uD808\uDE7D\uD808\uDD2C"},
	{"signName":"bulug3", "cuneiform":"pap-pap", "cuneiform1":"pab-pab", "val":"\uD808\uDE7D\uD808\uDE7D"},
	{"signName":"pab-isz", "cuneiform":"pap-isz", "cuneiform1":"pa6", "val":"\uD808\uDE7D\uD808\uDD56"},
	{"signName":"pab-e", "cuneiform":"pap-e", "cuneiform1":"pa5", "val":"\uD808\uDE7D\uD808\uDC8A"},
	{"signName":"NUMUN", "cuneiform":"zi-zi-lagab", "cuneiform1":"numun2", "val":"\uD808\uDF64\uD808\uDCB8"},
	{"signName":"zi-zi-sze3", "cuneiform":"zi-zi-esz2", "val":"\uD808\uDF64\uD808\uDCA0"},
	{"signName":"zi-zi-a", "val":"\uD808\uDF64\uD808\uDC00"},
	{"signName":"kunga2", "cuneiform":"bar-an", "val":"\uD808\uDC47\uD808\uDC2D"},
	{"signName":"idigna", "cuneiform":"dalla", "cuneiform1":"masz-gu2-gar3", "val":"\uD808\uDE26\uD808\uDD18\uD808\uDCFC"},
	{"signName":"gidim2", "cuneiform":"masz-u", "val":"\uD808\uDE26\uD808\uDF0B"},
	{"signName":"masz-man", "cuneiform":"masz-u-u", "val":"\uD808\uDE26\uD808\uDF0B\uD808\uDF0B"},
	{"signName":"buru5", "cuneiform":"nam-erim", "cuneiform1":"nam-erin2", "val":"\uD808\uDE46\uD808\uDC9F"},
	{"signName":"mud", "cuneiform":"hu-hi", "val":"\uD808\uDD37\uD808\uDD2D"},
	{"signName":"sa4", "cuneiform":"hu-na2", "val":"\uD808\uDD37\uD808\uDE3F"},
	{"signName":"tur3", "cuneiform":"nun-lagar", "val":"\uD808\uDE63\uD808\uDDEC"},
	{"signName":"gad-kid2", "cuneiform":"gad-tak4", "val":"\uD808\uDCF0\uD808\uDEFA"},
	{"signName":"akkil", "cuneiform":"gad-kid2-si", "cuneiform1":"gad-tak4-si", "val":"\uD808\uDCF0\uD808\uDEFA\uD808\uDEDB"},
	{"signName":"sig8", "cuneiform":"gad-kid2-gisz", "cuneiform1":"gad-tak4-gisz", "val":"\uD808\uDCF0\uD808\uDEFA\uD808\uDD11"},
	{"signName":"gun", "cuneiform":"gu2-un", "val":"\uD808\uDD18\uD808\uDF27"},
	{"signName":"dimgul", "cuneiform":"ma2-mug", "val":"\uD808\uDE23\uD808\uDE2E"},
	{"signName":"dir", "cuneiform":"si-a", "val":"\uD808\uDEDB\uD808\uDC00"},
	{"signName":"megidda", "cuneiform":"tab-ti", "val":"\uD808\uDEF0\uD808\uDEFE"},
	{"signName":"megidda2", "cuneiform":"tab-kun", "val":"\uD808\uDEF0\uD808\uDDB2"},
	{"signName":"tur-disz", "val":"\uD808\uDF09\uD808\uDC79"},
	{"signName":"dim8", "cuneiform":"rab-gan", "val":"\uD808\uDE90\uD808\uDCF6"},
	{"signName":"dim3", "cuneiform":"rab-gam", "val":"\uD808\uDE90\uD808\uDCF5"},
	{"signName":"dim9", "cuneiform":"lugal-gan", "val":"\uD808\uDE17\uD808\uDCF6"},
	{"signName":"iti3", "cuneiform":"kaskal-iti", "val":"\uD808\uDD9C\uD808\uDF1A"},
	{"signName":"illat", "cuneiform":"kaskal-kur", "val":"\uD808\uDD9C\uD808\uDDB3"},
	{"signName":"zikura", "cuneiform":"kaskal-asz3", "val":"\uD808\uDD9C\uD809\uDC0B"},
	{"signName":"na4", "val":"\uD808\uDE4C\uD808\uDF13"},
	{"signName":"dag3", "val":"\uD808\uDE4C\uD808\uDC9F"},
	{"signName":"szita2", "val":"\uD808\uDED6\uD808\uDD11"},
	{"signName":"szab", "val":"\uD808\uDE7A\uD808\uDD41"},
	{"signName":"nuska", "val":"\uD808\uDE7A\uD808\uDF06"},
	{"signName":"sipa", "val":"\uD808\uDE7A\uD808\uDDFB"},
	{"signName":"ia9", "val":"\uD808\uDC3C\uD808\uDEF0"},
	{"signName":"us", "cuneiform":"uz", "val":"\uD808\uDEBA\uD808\uDD37"},
	{"signName":"kar", "val":"\uD808\uDEFC\uD808\uDC00"},
	{"signName":"hus", "val":"\uD808\uDD2D\uD808\uDD0A"},
	{"signName":"udun", "val":"\uD808\uDF0B\uD808\uDE2C"},
	{"signName":"szibir", "val":"\uD808\uDF0B\uD808\uDC98"},
	{"signName":"gakkul3", "val":"\uD808\uDF0B\uD808\uDC74"},
	{"signName":"gakkul", "val":"\uD808\uDF0B\uD808\uDC75"},
	{"signName":"aszdar", "val":"\uD808\uDF0B\uD808\uDC6F"},
	{"signName":"sagszu", "val":"\uD808\uDF0B\uD808\uDE95"},
	{"signName":"gir4", "val":"\uD808\uDF0B\uD808\uDC1C"},
	{"signName":"szagan", "val":"\uD808\uDF0B\uD808\uDCF6"},
	{"signName":"szita4", "val":"\uD808\uDF0B\uD808\uDDA4"},
	{"signName":"utu2", "val":"\uD808\uDF0B\uD808\uDCB5"},
	{"signName":"gig", "val":"\uD808\uDE2A\uD808\uDE6D"},
	{"signName":"nigin4", "val":"\uD808\uDF0B\uD808\uDF13"},
	{"signName":"nigin3", "val":"\uD808\uDF0B\uD808\uDF13\uD808\uDDA4"},
	{"signName":"man", "val":"\uD808\uDF0B\uD808\uDF0B"},
	{"signName":"u-u-gunu", "val":"\uD808\uDF0B\uD809\uDC34"},
	{"signName":"kuszu", "val":"\uD808\uDF0B\uD808\uDD0A\uD808\uDE8A"},
	{"signName":"dul", "val":"\uD808\uDF0B\uD808\uDF06"},
	{"signName":"pad3", "val":"\uD808\uDD46\uD808\uDE92"},
	{"signName":"agrig", "val":"\uD808\uDD46\uD808\uDC7E"},
	{"signName":"u6", "val":"\uD808\uDD46\uD808\uDC8D"},
	{"signName":"sig5", "cuneiform":"kurum7", "val":"\uD808\uDD46\uD808\uDC9F"},
	{"signName":"libir", "val":"\uD808\uDD46\uD808\uDCA0"},
	{"signName":"hul", "val":"\uD808\uDD46\uD808\uDF28"},
	{"signName":"hul4", "val":"\uD808\uDD46\uD808\uDF2A"},
	{"signName":"mesz", "val":"\uD808\uDE28\uD808\uDF0D"},
	{"signName":"nigin", "val":"\uD808\uDDB8\uD808\uDDB8"},
	{"signName":"nenni", "val":"\uD808\uDDE7\uD808\uDDE7"},
	{"signName":"munszub2", "val":"\uD808\uDEC1\uD808\uDEE6"},
	{"signName":"iszszebu", "val":"\uD809\uDC08\uD808\uDF0B\uD808\uDF0B"},
	{"signName":"gug", "val":"\uD808\uDF5D\uD808\uDD22"},
	{"signName":"en2", "val":"\uD808\uDED9\uD808\uDC2D"},
	{"signName":"kesz3", "val":"\uD808\uDED9\uD808\uDC2D\uD808\uDD32"},
	{"signName":"kunga", "val":"\uD808\uDED9\uD808\uDC2F"},
	{"signName":"szeg8", "val":"\uD808\uDED9\uD808\uDE40"},
	{"signName":"lil5", "val":"\uD808\uDED9\uD808\uDE48"},
	{"signName":"gibil2", "val":"\uD808\uDED9\uD808\uDC3E"},
	{"signName":"szudun", "val":"\uD808\uDED9\uD808\uDC88"},
	{"signName":"lil3", "val":"\uD808\uDED9\uD808\uDF0D"},
	{"signName":"nin9", "val":"\uD808\uDEA9\uD808\uDDAA"},
	{"signName":"nin", "val":"\uD808\uDEA9\uD808\uDF06"},
	{"signName":"geme2", "val":"\uD808\uDEA9\uD808\uDDB3"},
	{"signName":"tugul", "val":"\uD808\uDE44\uD808\uDF5E"},
	{"signName":"egi2", "val":"\uD808\uDEA9\uD808\uDCA0"},
	{"signName":"nig", "val":"\uD808\uDEA9\uD808\uDF28"}
		];

    var toTranslateArea = $('.to-translate');
    var resultArea = $('.result');

    $('#translate').on('click', function(){
        $('.text-success').remove();
        var button = $(this);
        var toTranslateText = toTranslateArea.val();
        if (toTranslateText == ''){
            toTranslateArea.closest("div").addClass('has-error');
            toTranslateArea.attr('placeholder', 'Type the syllables here (e.g. asz bal hal an)');
        } else {
            translate(toTranslateText);
        }
    });

    toTranslateArea.on('keyup', function() {
        toTranslateArea.closest("div").removeClass('has-error');
    });

    var translate = function(needle){
        var result = '';
        var toTranslateArr = needle.split(" ");

        resultArea.val('');

        for (var j = 0; j < toTranslateArr.length; j++) {
            var flag = false;
            for (var i = 0; i < vocabulary.length; i++) {
                if (vocabulary[i].signName == toTranslateArr[j] || vocabulary[i].cuneiform == toTranslateArr[j] || vocabulary[i].cuneiform1 == toTranslateArr[j] || vocabulary[i].cuneiform2 == toTranslateArr[j] || vocabulary[i].cuneiform3 == toTranslateArr[j] || vocabulary[i].cuneiform4 == toTranslateArr[j] || vocabulary[i].cuneiform5 == toTranslateArr[j] || vocabulary[i].cuneiform6 == toTranslateArr[j] || vocabulary[i].cuneiform7 == toTranslateArr[j]) {
                    resultArea.closest("div").addClass('has-success');
                    resultArea.closest("div").removeClass('has-warning');
                    result += vocabulary[i].val;
                    if (j != toTranslateArr.length - 1) {
                        result += " ";
                    }
                    flag = true;
                }
            }

            if (!flag) {
                resultArea.closest("div").addClass('has-warning');
                resultArea.closest("div").removeClass('has-success');
                result += " "+toTranslateArr[j];
            }
        }

        resultArea.val(result);
    };

    $('#change-to-santakku').on('click', function(){
        $('.result').css('font-family','Santakku');
    });

    $('#change-to-akkadian').on('click', function(){
        $('.result').css('font-family','Akkadian');
    });
	
	$('#change-to-santakkum').on('click', function(){
        $('.result').css('font-family','SantakkuM');
    });

	$('#change-to-zarathustra').on('click', function(){
        $('.result').css('font-family','Zarathustra');
    });

	$('#change-to-DhUgaritic').on('click', function(){
        $('.result').css('font-family','DhUgaritic');
    });
});
